### ISSUE TITLE
clojure.test.mode, having doubles in a (is ..) statement hangs the REPL

### ISSUE THREAD

**Issue by martintrojer** [clojure-emacs/cider#1138]
`; CIDER 0.9.0 (Java 1.8.0_45, Clojure 1.6.0, nREPL 0.2.10)`

```clj
(deftest a-test
  (testing "FIXME, I fail."
    (is (= 0 1.0))))
```
Then
`C-c ,`

From `*nrepl-server*` buffer

```
ERROR: Unhandled REPL handler exception processing message {:ns foo.core-test, :op test, :tests [], :session ae6c8ff7-4158-44e9-83d4-7a9fdf63dfdf, :id 13}
java.lang.IllegalArgumentException: Cannot write value of type class java.lang.Double
	at clojure.tools.nrepl.bencode$eval68$fn__69.invoke(bencode.clj:326)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at clojure.tools.nrepl.bencode$eval93$fn__94.invoke(bencode.clj:382)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at clojure.tools.nrepl.bencode$eval93$fn__94.invoke(bencode.clj:382)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at clojure.tools.nrepl.bencode$eval103$fn__104.invoke(bencode.clj:398)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
```

**Comment by bbatsov** [comment]
Tried to reproduce this, but it works just fine for me.

```
; CIDER 0.9.1snapshot (package: 20150618.2308) (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.10)
```

Our setups looks similar, so I wonder what might be causing this for you.

**Comment by martintrojer** [comment]
The bug is caused by this (in my lean profiles)

https://github.com/pjstadig/humane-test-output
