### ISSUE TITLE
"Unhandled REPL handler exception" when re-connect to existing repl

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/cider#1386]
cider 20151027.739
clojure 1.7.0

Try to connect to existing repl via cider-connect, end up session (eg. by killing buffer) and connect again. Following stacktrace is thrown in repl:

```
ERROR |  Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :id 7}
java.net.SocketException: Socket closed
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116) ~[na:1.8.0_65]
at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0_65]
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_65]
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_65]
at clojure.tools.nrepl.transport$bencode$fn__24771.invoke(transport.clj:103) ~[na:na]
at clojure.tools.nrepl.transport.FnTransport.send(transport.clj:28) ~[na:na]
at clojure.tools.nrepl.middleware.pr_values$pr_values$fn$reify__25128.send(pr_values.clj:27) ~[na:na]
at cemerick.piggieback$cljs_ns_transport$reify__28951.send(piggieback.clj:236) ~[na:na]
at cider.nrepl.middleware.debug$debugger_send.doInvoke(debug.clj:148) ~[na:na]
at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.7.0.jar:na]
at cider.nrepl.middleware.debug$initialize.invoke(debug.clj:310) ~[na:na]
at cider.nrepl.middleware.debug$wrap_debug$fn__30705.invoke(debug.clj:338) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at boot.repl_server$wrap_init_ns$fn__25422$fn__25424.invoke(repl_server.clj:33) ~[na:na]
at cider.nrepl.middleware.trace$wrap_trace$fn__34566.invoke(trace.clj:65) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.classpath$wrap_classpath$fn__29009.invoke(classpath.clj:24) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.format$wrap_format$fn__33543.invoke(format.clj:58) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__25327.invoke(load_file.clj:79) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cemerick.piggieback$wrap_cljs_repl$fn__28956$fn__28958.invoke(piggieback.clj:255) ~[na:na]
at clojure.lang.AFn.applyToHelper(AFn.java:152) [clojure-1.7.0.jar:na]
at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:na]
at clojure.core$apply.invoke(core.clj:630) ~[clojure-1.7.0.jar:na]
at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868) ~[clojure-1.7.0.jar:na]
at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.7.0.jar:na]
at cemerick.piggieback$wrap_cljs_repl$fn__28956.invoke(piggieback.clj:252) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.out$wrap_out$fn__34008.invoke(out.clj:96) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.track_state$wrap_tracker$fn__34908.invoke(track_state.clj:201) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.pprint$wrap_pprint$fn__34039.invoke(pprint.clj:51) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.inspect$wrap_inspect$fn__30449.invoke(inspect.clj:108) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__25125.invoke(pr_values.clj:22) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at cider.nrepl.middleware.test$wrap_test$fn__34302.invoke(test.clj:220) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at clojure.tools.nrepl.middleware.session$session$fn__25271.invoke(session.clj:192) ~[na:na]
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__24942.invoke(middleware.clj:22) ~[na:na]
at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19) ~[na:na]
at clojure.tools.nrepl.server$handle$fn__25342.invoke(server.clj:28) [na:na]
at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916) [clojure-1.7.0.jar:na]
at clojure.lang.AFn.call(AFn.java:18) [clojure-1.7.0.jar:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

**Comment by bbatsov** [comment]
@Malabarba will you take a look at this?

**Comment by Malabarba** [comment]
Yes. I'm a little flooded right now. But ping me again if I haven't fixed it when release approaches.

**Comment by Malabarba** [comment]
Would also be good to know a way to detect closed connections.

**Comment by bbatsov** [comment]
Is this still a problem?

**Comment by Malabarba** [comment]
I don't believe anything has fixed it. @mbuczko could you test to see if it's still a problem? If so I think I have an idea of how to fix it.

**Comment by mbuczko** [comment]
yup, it still exists on newest cider.

**Comment by vspinu** [comment]
I cannot reproduce this. It might have been "auto-fixed".

**Comment by FrankApiyo** [comment]
I'm still experiencing this in 2020, not sure if there's something I'm doing wrong in my build.boot file

**Comment by FrankApiyo** [comment]
```
(set-env!
 :source-paths #{"src/cljs"}
 :resource-paths #{"html"}
 
 :dependencies '[
                 [org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.473"]
                 [adzerk/boot-cljs "1.7.228-2"]
                 [pandeiro/boot-http "0.8.3"]
                 [org.clojure/tools.nrepl "0.2.12"]
                 [adzerk/boot-reload "0.5.1"]
                 [adzerk/boot-cljs-repl "0.3.3"]
                 [com.cemerick/piggieback "0.2.1"]
                 [weasel "0.7.0"]
                 ])

(require '[adzerk.boot-cljs :refer [cljs]]
         '[pandeiro.boot-http :refer [serve]]
         '[adzerk.boot-reload :refer [reload]]
         '[adzerk.boot-cljs-repl :refer [cljs-repl start-repl]])
```

**Comment by FrankApiyo** [comment]
changing `com.cemerick/piggieback "0.4.2"` to `cider/piggieback "0.4.0"`  and updating the `boot-cljs-repl` version to the latest one seems to work for me. :smiley:
