### ISSUE TITLE
The error stacktrace is not enouth

### ISSUE THREAD

**Issue by paomian** [clojure-emacs/cider#1514]
when i run reload by `C-c C-x`

and i get the error : 

``` clojure
Show: Clojure Java REPL Tooling Duplicates All  (0 frames hidden)

2. Unhandled clojure.lang.ArityException

1. Caused by clojure.lang.Compiler$CompilerException
   Wrong number of args (0) passed to: core/identity

                 Compiler.java: 7142  clojure.lang.Compiler/load
                       RT.java:  370  clojure.lang.RT/loadResourceScript
                       RT.java:  361  clojure.lang.RT/loadResourceScript
                       RT.java:  440  clojure.lang.RT/load
                       RT.java:  411  clojure.lang.RT/load
                      core.clj: 5641  clojure.core/load/fn
                      core.clj: 5640  clojure.core/load
                   RestFn.java:  408  clojure.lang.RestFn/invoke
                      core.clj: 5446  clojure.core/load-one
                      core.clj: 5486  clojure.core/load-lib/fn
                      core.clj: 5485  clojure.core/load-lib
                   RestFn.java:  142  clojure.lang.RestFn/applyTo
                      core.clj:  626  clojure.core/apply
                      core.clj: 5524  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  626  clojure.core/apply
                      core.clj: 5607  clojure.core/require
                   RestFn.java:  421  clojure.lang.RestFn/invoke
                    reload.clj:   35  mranderson046.toolsnamespace.v0v2v11.clojure.tools.namespace.reload/track-reload-one
                    reload.clj:   52  mranderson046.toolsnamespace.v0v2v11.clojure.tools.namespace.reload/track-reload
                   refresh.clj:  142  cider.nrepl.middleware.refresh/refresh-reply/fn
                      core.clj: 1913  clojure.core/binding-conveyor-fn/fn
                      AFn.java:  154  clojure.lang.AFn/applyToHelper
                   RestFn.java:  132  clojure.lang.RestFn/applyTo
                    Agent.java:  114  clojure.lang.Agent$Action/doRun
                    Agent.java:  163  clojure.lang.Agent$Action/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run
```

I can't know where is error :confounded: I just know the function `indentity` args nuber is 0

cider version is 0.10.1
cider/cider-nrepl version is 0.10.1

**Comment by bbatsov** [comment]
That's interesting. Do you have any reliable steps to reproduce the problem?

**Comment by Malabarba** [comment]
There's probably an identity being called with 0 args in one of your files.

**Comment by paomian** [comment]
@bbatsov In my project it will be reproduce inevitable.

@Malabarba yes,it just a test to reproduce the problem.

**Comment by Malabarba** [comment]
Ah. Now I understand your bug report. :-)
Sadly, I don't think there's much cider can do. That exception is being produced by clojure or tools.nrepl, not by cider.

**Comment by paomian** [comment]
I think that cider is not get the error message enough in version `0.10.1`
for example:
I run `lein repl` in my project,and then,i run `cider-connect` to connect this nrepl server.and produce an error.
`(.printStackTrace *e)` will be print  in nrepl
```clojure
java.lang.RuntimeException: Unable to resolve symbol: mobilePhoneNumberr in this context, compiling:(myproject/sms.clj:97:11)
	at clojure.lang.Compiler.analyze(Compiler.java:6464)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.access$100(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
        ..........
	at clojure.core$eval.invoke(core.clj:2927)
	at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
	at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
	at clojure.main$repl$fn__6634.invoke(main.clj:257)
	at clojure.main$repl.doInvoke(main.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__919.invoke(interruptible_eval.clj:103)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__964$fn__967.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__959.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: mobilePhoneNumberr in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6940)
	at clojure.lang.Compiler.resolve(Compiler.java:6884)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6845)
	at clojure.lang.Compiler.analyze(Compiler.java:6427)
	... 207 more
```
It can tell me where is error.`(myproject/sms.clj:97:11)`

-----------------------
but in cider,I just get `Unable to resolve symbol: mobilePhoneNumberr in this context`
```clojure
  Show: Clojure Java REPL Tooling Duplicates All  (52 frames hidden)

2. Unhandled java.lang.RuntimeException
  
1. Caused by clojure.lang.Compiler$CompilerException
   Unable to resolve symbol: mobilePhoneNumberr in this context

                 Compiler.java: 6464  clojure.lang.Compiler/analyze
                 Compiler.java: 6406  clojure.lang.Compiler/analyze
                 ................
                 Compiler.java: 7130  clojure.lang.Compiler/load
```

**Comment by bbatsov** [comment]
@jeffvalk can you take a look at this?

**Comment by jeffvalk** [comment]
@paomian Could you post a minimal code sample to reproduce this?

**Comment by paomian** [comment]
@jeffdik `lein new someproject` and do like this
```clojure
(defn foo
  "I don't do a whole lot."
  [x]
  (prin x "Hello, World!"))

```

```clojure

  Show: Clojure Java REPL Tooling Duplicates All  (31 frames hidden)

2. Unhandled java.lang.RuntimeException
   Unable to resolve symbol: prin in this context


1. Caused by clojure.lang.Compiler$CompilerException
   Unable to resolve symbol: prin in this context

                 Compiler.java: 6543  clojure.lang.Compiler/analyze
                 Compiler.java: 6485  clojure.lang.Compiler/analyze
                 Compiler.java: 3737  clojure.lang.Compiler$InvokeExpr/parse
                 Compiler.java: 6725  clojure.lang.Compiler/analyzeSeq
                 Compiler.java: 6524  clojure.lang.Compiler/analyze
                 Compiler.java: 6485  clojure.lang.Compiler/analyze
                 Compiler.java: 5861  clojure.lang.Compiler$BodyExpr$Parser/parse
                 Compiler.java: 5296  clojure.lang.Compiler$FnMethod/parse
                 Compiler.java: 3925  clojure.lang.Compiler$FnExpr/parse
                 Compiler.java: 6721  clojure.lang.Compiler/analyzeSeq
                 Compiler.java: 6524  clojure.lang.Compiler/analyze
                 Compiler.java: 6711  clojure.lang.Compiler/analyzeSeq
                 Compiler.java: 6524  clojure.lang.Compiler/analyze
                 Compiler.java:   38  clojure.lang.Compiler/access$300
                 ..........
                      core.clj:  632  clojure.core/apply
                      core.clj: 5749  clojure.core/load-libs
                   RestFn.java:  137  clojure.lang.RestFn/applyTo
                      core.clj:  632  clojure.core/apply
                      core.clj: 5832  clojure.core/require
                   RestFn.java:  421  clojure.lang.RestFn/invoke
                    reload.clj:   35  mranderson046.toolsnamespace.v0v2v11.clojure.tools.namespace.reload/track-reload-one
                    reload.clj:   52  mranderson046.toolsnamespace.v0v2v11.clojure.tools.namespace.reload/track-reload
                   refresh.clj:  143  cider.nrepl.middleware.refresh/refresh-reply/fn
                      core.clj: 1919  clojure.core/binding-conveyor-fn/fn
                      AFn.java:  154  clojure.lang.AFn/applyToHelper
                   RestFn.java:  132  clojure.lang.RestFn/applyTo
                    Agent.java:  114  clojure.lang.Agent$Action/doRun
                    Agent.java:  163  clojure.lang.Agent$Action/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run
```

my profiles.clj
```clojure
{:user {:plugins [[cider/cider-nrepl "0.10.1"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}
```

**Comment by bbatsov** [comment]
Our Jeff is @jeffvalk. :-)

**Comment by jeffvalk** [comment]
Will take a look at this.

**Comment by jeffvalk** [comment]
I don't see anything unusual here.

This:
```clj
(def x (identity))
```
gives me this:

```
  Show: Clojure Java REPL Tooling Duplicates All  (12 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling core.clj at (7:8)

1. Caused by clojure.lang.ArityException
   Wrong number of args (0) passed to: core/identity

                  AFn.java:  429  clojure.lang.AFn/throwArity
                  AFn.java:   28  clojure.lang.AFn/invoke
                      REPL:    1  user/eval9736
                  core.clj: 3081  clojure.core/eval
                  ...
               Thread.java:  745  java.lang.Thread/run
```

and this:
```clj
(defn foo [x]
  (println x an-undefined-thing))
```
gives me this:
```

  Show: Clojure Java REPL Tooling Duplicates All  (31 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling src/xyz/core.clj at (4:3)

1. Caused by java.lang.RuntimeException
   Unable to resolve symbol: an-undefined-thing in this context

                 Util.java:  221  clojure.lang.Util/runtimeException
             Compiler.java: 7019  clojure.lang.Compiler/resolveIn
             Compiler.java: 6963  clojure.lang.Compiler/resolve
             Compiler.java: 6924  clojure.lang.Compiler/analyzeSymbol
             Compiler.java: 6506  clojure.lang.Compiler/analyze
             Compiler.java: 6485  clojure.lang.Compiler/analyze
             Compiler.java: 3791  clojure.lang.Compiler$InvokeExpr/parse
             ...
               Thread.java:  745  java.lang.Thread/run
```
This all looks right to me.

**Comment by bbatsov** [comment]
Yep, this looks totally fine to me.

**Comment by paomian** [comment]
which cider version do you use ? my cider always don't show the line number to me.

**Comment by bbatsov** [comment]
I'm closing this ticket due to no recent activity. Feel free to re-open it if you ever come back to it.
