### ISSUE TITLE
Problems running a node repl env for Clojurescript development

### ISSUE THREAD

**Issue by woggle23** [clojure-emacs/cider#1764]
## Expected behavior
When launching `cider-jack-in-clojurescript`, a `cljs` `repl` should be generated displaying:
```
To quit, type: :cljs/quit
cljs.user=>
```
Which will evaluate `cljs` functions.

## Actual behavior
The `cljs` `repl` launches, but the prompt is:
```
user=>
```
Evaluating anything, even simply hitting `<cr>` causes the evaluation to hang. Hitting `Ctrl-c` (a few times) after a while yields the following:
```
java.lang.NullPointerException
	at cljs.repl.node$write.invoke(node.clj:38)
	at cljs.repl.node$node_eval.invoke(node.clj:59)
	at cljs.repl.node.NodeEnv._evaluate(node.clj:206)
	at user.Delegatingcljs_repl_node_NodeEnv._evaluate(form-init4800242380777067762.clj:122)
	at cljs.repl$load_namespace.invoke(repl.cljc:208)
	at cljs.repl$load_dependencies.invoke(repl.cljc:217)
	at cljs.repl$evaluate_form.invoke(repl.cljc:485)
	at cljs.repl$eval_cljs.invoke(repl.cljc:570)
	at cljs.repl$repl_STAR_$read_eval_print__7260.invoke(repl.cljc:875)
	at cljs.repl$repl_STAR_$fn__7266$fn__7275.invoke(repl.cljc:916)
	at cljs.repl$repl_STAR_$fn__7266.invoke(repl.cljc:915)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1154)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:877)
	at cemerick.piggieback$run_cljs_repl.invoke(piggieback.clj:169)
	at cemerick.piggieback$cljs_repl.doInvoke(piggieback.clj:222)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at user$eval16787.invoke(form-init4800242380777067762.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__634.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
To quit, type: :cljs/quit
nil
cljs.user> 
```

## Steps to reproduce the problem
Update `repl` environment:

`M-x`
`customize-variable`
`cider-cljs-lein-repl`

Select and Save `node` from the list

Lanuch the repl:

`cider-jack-in-clojurescript`

Please note, when launching the `repl` directly from the commandline, everything works fine, e.g:

Running `rlwrap lein noderepl`
 
With the following alias in `project.clj` `{"noderepl" ["run" "-m" "clojure.main" "repl.clj"]}`

The contents of `repl.clj` are as follows:
```
(require 'cljs.repl)
(require `cljs.repl.node)
(cljs.repl/repl (cljs.repl.node/repl-env))
```

## Environment & Version information
Note, initially when attempting to use the `node repl env` I had `$PATH` issues; `node` couldn't be found. For some reason the PATH, defined in `~/.bash_profile` was different to that used by emacs. I added the following my `~/.emacs.d/personal/mf-cider.el` script; which resolved the issue.

`(setenv "PATH" <MY_PATH_STRING>)`

Following this I encountered the issue highlighted above.

### CIDER version information

;; CIDER 0.13.0snapshot (package: 20160501.1921), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_92

### Lein version

*Lein 2.6.1

### Emacs version

*Emacs 24.5 (9.0)

### Operating system

Mac OSX El Capitan v 10.11.4

**Comment by woggle23** [comment]
OK, it looks like it was still some `$PATH` related issue. Although it managed to find `node` it clearly still wasn't happy. I reinstalled node to `/usr/local/bin` (not sure why it wasn't installed there in the first place TBH); problem resolved.

Cheers
