### ISSUE TITLE
CIDER middleware conflict with zprint as a dev dependency

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/cider#1921]
Adding [zprint](https://github.com/kkinnear/zprint) as a dev dependency causes CIDER middleware to throw when trying to start a REPL. Adding it as a regular project dependency does not cause the same issue.

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.macroexpand/wrap-macroexpand in this context, compiling:(C:\Users\Olli\AppData\Local\Temp\form-init755829693141095127.clj:1:9531)
```

See full stacktrace at the bottom of the post.

I've created an issue here as well as I'm not sure which project it's relevant for:

https://github.com/kkinnear/zprint/issues/19

## Steps to reproduce the problem

1) Add `:dependencies [[zprint "0.2.12"]]` in the `:dev` profile of a project, or via `profiles.clj` in Leiningen.
2) Try to launch REPL via `cider-jack-in`

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20170104.1330), nREPL 0.2.12
;; Clojure 1.9.0-alpha14, Java 1.8.0_91
```

### Lein/Boot version

Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM

### Operating system

Windows 10

## Full Stacktrace

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.macroexpand/wrap-macroexpand in this context, compiling:(C:\Users\Olli\AppData\Local\Temp\form-init755829693141095127.clj:1:9531)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6926)
  at clojure.lang.Compiler.analyze(Compiler.java:6701)
  at clojure.lang.Compiler.analyze(Compiler.java:6657)
  at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3835)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)
  at clojure.lang.Compiler.analyze(Compiler.java:6701)
  at clojure.lang.Compiler.analyze(Compiler.java:6657)
  at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3835)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)
  at clojure.lang.Compiler.analyze(Compiler.java:6701)
  at clojure.lang.Compiler.access$300(Compiler.java:38)
  at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6298)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6919)
  at clojure.lang.Compiler.analyze(Compiler.java:6701)
  at clojure.lang.Compiler.analyze(Compiler.java:6657)
  at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)
  at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)
  at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6917)
  at clojure.lang.Compiler.analyze(Compiler.java:6701)
  at clojure.lang.Compiler.eval(Compiler.java:6975)
  at clojure.lang.Compiler.eval(Compiler.java:6968)
  at clojure.lang.Compiler.load(Compiler.java:7430)
  at clojure.lang.Compiler.loadFile(Compiler.java:7368)
  at clojure.main$load_script.invokeStatic(main.clj:277)
  at clojure.main$init_opt.invokeStatic(main.clj:279)
  at clojure.main$init_opt.invoke(main.clj:279)
  at clojure.main$initialize.invokeStatic(main.clj:310)
  at clojure.main$null_opt.invokeStatic(main.clj:344)
  at clojure.main$null_opt.invoke(main.clj:341)
  at clojure.main$main.invokeStatic(main.clj:423)
  at clojure.main$main.doInvoke(main.clj:386)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.lang.Var.applyTo(Var.java:700)
  at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.macroexpand/wrap-macroexpand in this context
  at clojure.lang.Util.runtimeException(Util.java:221)
  at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:710)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6919)
  ... 34 more
Subprocess failed
```

**Comment by kkinnear** [comment]
I'm the person who maintains zprint, and I'd be delighted to work with someone to figure this out.  I expect that some library on which I am depending is interacting badly with something in CIDER, but I don't have a clue as to what.  Not being a CIDER user, I'm not going to be all that deft at figuring out what is going wrong here, so if someone has some idea of the actual problem I'd love to hear about it.

**Comment by xiongtx** [comment]
I can `cider-jack-in` fine with a stock `lein new` project that has the following `project.clj`:

```clojure
(defproject zprint-bug "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :profiles {:dev {:dependencies [[zprint "0.2.12"]]}})
```

Version info:

- Java 1.8.0_111
- Clojure 1.8.0
- CIDER 0.15.0snapshot (package: 20170111.138)
- nREPL 0.2.12

Can you put up a minimal project that demonstrates the problem?

**Comment by expez** [comment]
>  I expect that some library on which I am depending is interacting badly with something in CIDER

We do source rewriting to prevent this from happening.

**Comment by luxbock** [comment]
Sorry, turns out I had overlooked my `profiles.clj` dependencies, where I had something pulling in an older version of `tools.reader` which ended up blowing up when used with `zprint` and `CIDER`. I will close this.
