### ISSUE TITLE
Test all project tests

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/cider#1940]
## Expected behavior

Run all project tests should pop up a dialog

## Actual behavior

Nothing happens, but I get an exception in `*nrepl-server*`

      nREPL server started on port 42019 on host 127.0.0.1 - nrepl://127.0.0.1:42019
      Exception in thread "nREPL-worker-6" java.lang.Error: java.lang.Exception: No namespace: sio-header found
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      	at java.lang.Thread.run(Thread.java:745)
      Caused by: java.lang.Exception: No namespace: sio-header found
      	at clojure.core$the_ns.invokeStatic(core.clj:4032)
      	at clojure.core$the_ns.invoke(core.clj:4023)
      	at cider.nrepl.middleware.test$has_tests_QMARK_.invokeStatic(test.clj:183)
      	at cider.nrepl.middleware.test$has_tests_QMARK_.invoke(test.clj:179)
      	at clojure.core$filter$fn__4812.invoke(core.clj:2712)
      	at clojure.lang.LazySeq.sval(LazySeq.java:40)
      	at clojure.lang.LazySeq.seq(LazySeq.java:49)
      	at clojure.lang.RT.seq(RT.java:521)
      	at clojure.core$seq__4357.invokeStatic(core.clj:137)
      	at clojure.core$zipmap.invokeStatic(core.clj:2962)
      	at clojure.core$zipmap.invoke(core.clj:2962)
      	at cider.nrepl.middleware.test$handle_test_all$fn__19243$fn__19244.invoke(test.clj:231)
      	at clojure.lang.AFn.applyToHelper(AFn.java:152)
      	at clojure.lang.AFn.applyTo(AFn.java:144)
      	at clojure.core$apply.invokeStatic(core.clj:646)
      	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
      	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
      	at clojure.lang.RestFn.invoke(RestFn.java:425)
      	at cider.nrepl.middleware.test$handle_test_all$fn__19243.invoke(test.clj:230)
      	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__688.invoke(interruptible_eval.clj:190)
      	at clojure.lang.AFn.run(AFn.java:22)
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      	... 2 more

## Steps to reproduce the problem

I am seeing the stack trace shown when trying to run all project tests.

I have a slightly odd test which loads a namespace as part of the test. The
namespace is not inside the standard src or tests directory but in
dev-resources, which appears to be the cause of the problem. I cannot find a
simple reproduction, unfortuately, outside of this environment.

Cider gives no indication that this error has occurred, but the test report
never appears.

The cause of the error appears to be in this code:

      (defn has-tests?
        "Return a truthy value if the namespace has any `:test` metadata."
        [ns]
        (seq (filter (comp :test meta val)
                     (ns-interns (the-ns ns)))))
      

which is dependent on the-ns not excepting. Possible solutions are to use
"find-ns" instead and handling nil (assuming it's always passed a symbol), or
using a function which doesn't throw the exception in the first place.

### CIDER version information

```
; Connected to nREPL server - nrepl://localhost:42950
;; CIDER 0.13.0snapshot (package: 0.14.0), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_111
```

### Lein/Boot version
2.7.1
### Emacs version

Emacs 25.1 (self-compiled, running off 25 head)

### Operating system
lubuntu 16.10

**Comment by bbatsov** [comment]
> which is dependent on the-ns not excepting. Possible solutions are to use
> "find-ns" instead and handling nil (assuming it's always passed a symbol), or
> using a function which doesn't throw the exception in the first place.

That sounds reasonable to me. I'd appreciate it if you tried to prepare a PR for this. On a related note - seems we're also missing some general unexpected error handling code in this middleware, otherwise the problem wouldn't have manifested the way that it did.

**Comment by phillord** [comment]
I'll try and do a fix for this. And, yes, of course, you are correct, it would make sense for their to be some error handling further up the tree somewhere.
