### ISSUE TITLE
`cider-jack-in` is broken on Windows?

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/cider#2122]
## Steps to reproduce the problem

1. install software in the versions shown below
2. run `cider-jack-in`
3. ???
4. don't profit

### CIDER version information

`0.15.1`

### Lein/Boot version

Leiningen 2.8.1 on Java 9.0.1 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24

### Operating system

Windows 10

## Stacktrace

```
Starting nREPL server via "c:/Users/zilti/bin/lein.bat" update-in :dependencies conj ^"[org.clojure/tools.nrepl \^"0.2.12\^" :exclusions [org.clojure/clojure]]^" -- update-in :plugins conj ^"[refactor-nrepl \^"2.3.1\^"]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.15.1\^"]^" -- repl :headless :host ::...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Retrieving mount/mount/0.1.11/mount-0.1.11.pom from clojars

Retrieving org/clojure/core.async/0.3.465/core.async-0.3.465.pom from central

Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.pom from central

Retrieving org/clojure/pom.contrib/0.2.0/pom.contrib-0.2.0.pom from central

Retrieving org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.pom from central

Retrieving org/clojure/clojure/1.5.1/clojure-1.5.1.pom from central

Retrieving org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.pom from central

Retrieving org/clojure/core.cache/0.6.5/core.cache-0.6.5.pom from central

Retrieving org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.pom from central

Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central

Retrieving org/ow2/asm/asm-all/4.2/asm-all-4.2.pom from central

Retrieving org/ow2/asm/asm-parent/4.2/asm-parent-4.2.pom from central

Retrieving org/ow2/ow2/1.3/ow2-1.3.pom from central

Retrieving org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4.pom from central

Retrieving org/clojure/clojure/1.7.0/clojure-1.7.0.pom from central

Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.jar from central

Retrieving org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar from central

Retrieving org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar from central

Retrieving org/clojure/core.async/0.3.465/core.async-0.3.465.jar from central

Retrieving org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar from central

Retrieving org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar from central

Retrieving org/ow2/asm/asm-all/4.2/asm-all-4.2.jar from central

Retrieving org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4.jar from central

Retrieving mount/mount/0.1.11/mount-0.1.11.jar from clojars

WARNING: boolean? already refers to: #’clojure.core/boolean? in namespace: mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils, being replaced by: #’mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils/boolean?

WARNING: boolean? already refers to: #’clojure.core/boolean? in namespace: mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer, being replaced by: #’mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils/boolean?

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by mranderson047.alembic.v0v3v3.dynapath.v0v2v5.dynapath.defaults$eval8776$fn__8777 to method java.net.URLClassLoader.addURL(java.net.URL)

WARNING: Please consider reporting this to the maintainers of mranderson047.alembic.v0v3v3.dynapath.v0v2v5.dynapath.defaults$eval8776$fn__8777

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

Error loading refactor-nrepl.middleware: clojure.lang.ExceptionInfo: Alembic can not manipulate specified ClassLoader. {:classloader #object[jdk.internal.loader.ClassLoaders$AppClassLoader 0x3fb4f649 "jdk.internal.loader.ClassLoaders$AppClassLoader@3fb4f649"], :reason :not-addable-with-dynapath}, compiling:(mranderson047/alembic/v0v3v3/alembic/still.clj:65:1)

Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(C:\Users\zilti\AppData\Local\Temp\form-init4379827143854056593.clj:1:7677)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.access$300(Compiler.java:38)

	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)

	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)

	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.eval(Compiler.java:7059)

	at clojure.lang.Compiler.eval(Compiler.java:7052)

	at clojure.lang.Compiler.load(Compiler.java:7514)

	at clojure.lang.Compiler.loadFile(Compiler.java:7452)

	at clojure.main$load_script.invokeStatic(main.clj:278)

	at clojure.main$init_opt.invokeStatic(main.clj:280)

	at clojure.main$init_opt.invoke(main.clj:280)

	at clojure.main$initialize.invokeStatic(main.clj:311)

	at clojure.main$null_opt.invokeStatic(main.clj:345)

	at clojure.main$null_opt.invoke(main.clj:342)

	at clojure.main$main.invokeStatic(main.clj:424)

	at clojure.main$main.doInvoke(main.clj:387)

	at clojure.lang.RestFn.applyTo(RestFn.java:137)

	at clojure.lang.Var.applyTo(Var.java:702)

	at clojure.main.main(main.java:37)

Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context

	at clojure.lang.Util.runtimeException(Util.java:221)

	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)

	... 34 more

Subprocess failed


error in process sentinel: Could not start nREPL server: Retrieving mount/mount/0.1.11/mount-0.1.11.pom from clojars

Retrieving org/clojure/core.async/0.3.465/core.async-0.3.465.pom from central

Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.pom from central

Retrieving org/clojure/pom.contrib/0.2.0/pom.contrib-0.2.0.pom from central

Retrieving org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.pom from central

Retrieving org/clojure/clojure/1.5.1/clojure-1.5.1.pom from central

Retrieving org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.pom from central

Retrieving org/clojure/core.cache/0.6.5/core.cache-0.6.5.pom from central

Retrieving org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.pom from central

Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central

Retrieving org/ow2/asm/asm-all/4.2/asm-all-4.2.pom from central

Retrieving org/ow2/asm/asm-parent/4.2/asm-parent-4.2.pom from central

Retrieving org/ow2/ow2/1.3/ow2-1.3.pom from central

Retrieving org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4.pom from central

Retrieving org/clojure/clojure/1.7.0/clojure-1.7.0.pom from central

Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.jar from central

Retrieving org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar from central

Retrieving org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar from central

Retrieving org/clojure/core.async/0.3.465/core.async-0.3.465.jar from central

Retrieving org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar from central

Retrieving org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar from central

Retrieving org/ow2/asm/asm-all/4.2/asm-all-4.2.jar from central

Retrieving org/clojure/tools.reader/1.0.0-beta4/tools.reader-1.0.0-beta4.jar from central

Retrieving mount/mount/0.1.11/mount-0.1.11.jar from clojars

WARNING: boolean? already refers to: #’clojure.core/boolean? in namespace: mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils, being replaced by: #’mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils/boolean?

WARNING: boolean? already refers to: #’clojure.core/boolean? in namespace: mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer, being replaced by: #’mranderson047.toolsanalyzerjvm.v0v6v9.toolsanalyzer.v0v6v7.clojure.tools.analyzer.utils/boolean?

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by mranderson047.alembic.v0v3v3.dynapath.v0v2v5.dynapath.defaults$eval8776$fn__8777 to method java.net.URLClassLoader.addURL(java.net.URL)

WARNING: Please consider reporting this to the maintainers of mranderson047.alembic.v0v3v3.dynapath.v0v2v5.dynapath.defaults$eval8776$fn__8777

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

Error loading refactor-nrepl.middleware: clojure.lang.ExceptionInfo: Alembic can not manipulate specified ClassLoader. {:classloader #object[jdk.internal.loader.ClassLoaders$AppClassLoader 0x3fb4f649 "jdk.internal.loader.ClassLoaders$AppClassLoader@3fb4f649"], :reason :not-addable-with-dynapath}, compiling:(mranderson047/alembic/v0v3v3/alembic/still.clj:65:1)

Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(C:\Users\zilti\AppData\Local\Temp\form-init4379827143854056593.clj:1:7677)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.access$300(Compiler.java:38)

	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.analyze(Compiler.java:6729)

	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)

	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)

	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)

	at clojure.lang.Compiler.analyze(Compiler.java:6773)

	at clojure.lang.Compiler.eval(Compiler.java:7059)

	at clojure.lang.Compiler.eval(Compiler.java:7052)

	at clojure.lang.Compiler.load(Compiler.java:7514)

	at clojure.lang.Compiler.loadFile(Compiler.java:7452)

	at clojure.main$load_script.invokeStatic(main.clj:278)

	at clojure.main$init_opt.invokeStatic(main.clj:280)

	at clojure.main$init_opt.invoke(main.clj:280)

	at clojure.main$initialize.invokeStatic(main.clj:311)

	at clojure.main$null_opt.invokeStatic(main.clj:345)

	at clojure.main$null_opt.invoke(main.clj:342)

	at clojure.main$main.invokeStatic(main.clj:424)

	at clojure.main$main.doInvoke(main.clj:387)

	at clojure.lang.RestFn.applyTo(RestFn.java:137)

	at clojure.lang.Var.applyTo(Var.java:702)

	at clojure.main.main(main.java:37)

Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context

	at clojure.lang.Util.runtimeException(Util.java:221)

	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)

	... 34 more

Subprocess failed

```

**Comment by bbatsov** [comment]
> Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(C:\Users\zilti\AppData\Local\Temp\form-init4379827143854056593.clj:1:7677)

I'm pretty sure removing `refactor-nrepl` will solve your problem. Perhaps that's some incompatible version that you're using or something. That's clearly not a problem in CIDER itself.

**Comment by zilti** [comment]
I have no profile.clj. 

My dependency vector in project.clj:
```
  :dependencies [[org.clojure/clojure "1.9.0-RC2"]
                 [mount "0.1.11"]
                 [org.clojure/core.async "0.3.465"]
                 [org.jmonkeyengine/jme3-core "3.1.0-stable"]
                 [org.jmonkeyengine/jme3-desktop "3.1.0-stable"]
                 [org.jmonkeyengine/jme3-lwjgl3 "3.1.0-stable"]]
```

Which leads to this deptree (executing `lein deps :tree`):
```
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [mount "0.1.11"]
 [org.clojure/clojure "1.9.0-RC2"]
   [org.clojure/core.specs.alpha "0.1.24"]
   [org.clojure/spec.alpha "0.1.143"]
 [org.clojure/core.async "0.3.465"]
   [org.clojure/tools.analyzer.jvm "0.7.0"]
     [org.clojure/core.memoize "0.5.9"]
       [org.clojure/core.cache "0.6.5"]
         [org.clojure/data.priority-map "0.0.7"]
     [org.clojure/tools.analyzer "0.6.9"]
     [org.clojure/tools.reader "1.0.0-beta4"]
     [org.ow2.asm/asm-all "4.2"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [org.jmonkeyengine/jme3-core "3.1.0-stable"]
 [org.jmonkeyengine/jme3-desktop "3.1.0-stable"]
 [org.jmonkeyengine/jme3-lwjgl3 "3.1.0-stable"]
   [org.lwjgl/lwjgl-platform "3.0.0b" :classifier "natives-linux"]
   [org.lwjgl/lwjgl-platform "3.0.0b" :classifier "natives-osx"]
   [org.lwjgl/lwjgl-platform "3.0.0b" :classifier "natives-windows"]
   [org.lwjgl/lwjgl "3.0.0b"]
```

**Comment by bbatsov** [comment]
Probably you've installed `clj-refactor` and it's auto-injecting its middleware.

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/clj-refactor.el/wiki/installation#optional-setup
