### ISSUE TITLE
Connecting too quickly can cause "namespace not found"

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/cider#2256]
In our team we're using a script that launches clj repl + cider, waits for it to be available, and then uses emacsclient to connect CIDER.

Regularly we'd see errors with mranderson-ized `clojure.tools.namespace` namespaces not being found. We eventually figured out that putting an extra `sleep` in there made the errors go away.

The script looks roughly like this (this is heavily simplified, it does quite a bit more)

``` shell
export JOURNAL_NREPL_PORT=7888

# Wait in the background for nREPL to be reachable, then connect Emacs/CIDER
bash <<EOF &
  while ! nc -z localhost $JOURNAL_NREPL_PORT ; do sleep 0.5; done
  # sleep 1
  emacsclient -e '(cider-connect "localhost" "'${JOURNAL_NREPL_PORT}'" "'`pwd`'")' >/dev/null && echo "CIDER connected!"
EOF

export JOURNAL_CIDER_VERSION=$(emacsclient -e '(upcase cider-version)' 2>/dev/null)

clj -Sdeps '{:deps {cider/cider-nrepl {:mvn/version '${JOURNAL_CIDER_VERSION}'}}}' -m server.repl
```

This error would show up in the `*cider-repl*` buffer. Putting a `sleep 1` before `cider-connect` made it go away.

This probably doesn't affect many people, but I figured it wouldn't hurt reporting this, since currently googling for these errors yields no useful information.

```
Unhandled REPL handler exception processing message {:op eldoc, :ns editor.core, :symbol println, :session f7092208-248c-4c8e-aab6-364b2c07f69b, :id 1548}
clojure.lang.Compiler$CompilerException: java.lang.Exception: namespace 'mranderson048.toolsnamespace.v0v3v0-alpha4.clojure.tools.namespace.parse' not found, compiling:(mranderson048/toolsnamespace/v0v3v0_alpha4/clojure/tools/namespace/file.clj:9:1)
	at clojure.core$throw_if.invokeStatic(core.clj:5807)
	at clojure.core$load_lib.invokeStatic(core.clj:5893)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at mranderson048.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval63949$loading__6434__auto____63950.invoke(file.clj:9)
	at mranderson048.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval63949.invokeStatic(file.clj:9)
	at mranderson048.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.file$eval63949.invoke(file.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.namespace$eval63941$loading__6434__auto____63942.invoke(namespace.clj:1)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.namespace$eval63941.invokeStatic(namespace.clj:1)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.namespace$eval63941.invoke(namespace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.meta$eval63933$loading__6434__auto____63934.invoke(meta.clj:1)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.meta$eval63933.invokeStatic(meta.clj:1)
	at mranderson048.orchard.v0v1v0_20180321v113210_28.orchard.meta$eval63933.invoke(meta.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:1096)
	at cider.nrepl.middleware.info$eval63925$loading__6434__auto____63926.invoke(info.clj:1)
	at cider.nrepl.middleware.info$eval63925.invokeStatic(info.clj:1)
	at cider.nrepl.middleware.info$eval63925.invoke(info.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.nrepl$run_deferred_handler$fn__57446.invoke(nrepl.clj:37)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at cider.nrepl$wrap_info$fn__57652.invoke(nrepl.clj:205)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_trace$fn__57742.invoke(nrepl.clj:432)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__57694.invoke(nrepl.clj:314)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_macroexpand$fn__57670.invoke(nrepl.clj:264)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_ns$fn__57678.invoke(nrepl.clj:277)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_classpath$fn__57610.invoke(nrepl.clj:135)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_complete$fn__57618.invoke(nrepl.clj:141)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_version$fn__57766.invoke(nrepl.clj:469)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_stacktrace$fn__57726.invoke(nrepl.clj:405)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__6169.invoke(interruptible_eval.clj:247)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_debug$fn__57628.invoke(nrepl.clj:161)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at server.nrepl_server$wrap_init_vars$fn__42923$fn__42925.invoke(nrepl_server.clj:48)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__6295.invoke(load_file.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_enlighten$fn__57636.invoke(nrepl.clj:187)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__6252.invoke(session.clj:238)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_spec$fn__57718.invoke(nrepl.clj:389)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_format$fn__57644.invoke(nrepl.clj:191)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_apropos$fn__57602.invoke(nrepl.clj:127)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cemerick.piggieback$wrap_cljs_repl$fn__57581.invoke(piggieback.clj:299)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_pprint$fn__57594.invoke(nrepl.clj:107)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_out$fn__57686.invoke(nrepl.clj:305)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_tracker$fn__57750.invoke(nrepl.clj:450)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_inspect$fn__57662.invoke(nrepl.clj:224)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__6085.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_resource$fn__57710.invoke(nrepl.clj:377)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl$wrap_test$fn__57734.invoke(nrepl.clj:415)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic(pprint.clj:49)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invoke(pprint.clj:44)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_pprint_fn$fn__57474.invoke(nrepl.clj:88)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__6237.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__5886.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__6310.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bbatsov** [comment]
I wonder if this has something to do with the deferred middleware loading. //cc @vspinu Guess we'll have to investigate.

**Comment by kommen** [comment]
We're still running into these errors, apparently more often on slower machines, where we have to increase the `sleep 1` to some higher number. Maybe somebody can give me a pointer where to start looking? Maybe I can shave off some time to investigate.
