### ISSUE TITLE
cider-repl-set-ns fails (to remote nREPL within Immutant)

### ISSUE THREAD

**Issue by terjesb** [clojure-emacs/cider#2287]
## Expected behavior

cider-repl-set-ns working.

## Actual behavior

C-c M-n fails:

2018-05-09 06:10:11,566 ERROR [clojure.tools.nrepl.server] (clojure-agent-send-off-pool-12) Unhandled REPL handler exception processing message {:op eval, :code (in-ns 'magegw.order-handler), :session 50dd6830-a109-4f43-86dc-26f7a5760c00, :id 9}: java.lang.Exception: namespace 'cider.inlined-deps.orchard.v0v2v0.orchard.java' not found, compiling:(cider/inlined_deps/orchard/v0v2v0/orchard/classloader.clj:1:1)
	at clojure.core$throw_if.invokeStatic(core.clj:5807)
	at clojure.core$load_lib.invokeStatic(core.clj:5893)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at cider.inlined_deps.orchard.v0v2v0.orchard.classloader$eval3538$loading__6434__auto____3539.invoke(classloader.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.classloader$eval3538.invokeStatic(classloader.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.classloader$eval3538.invoke(classloader.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at cider.inlined_deps.orchard.v0v2v0.orchard.namespace$eval2214$loading__6434__auto____2215.invoke(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.namespace$eval2214.invokeStatic(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.namespace$eval2214.invoke(namespace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at cider.inlined_deps.orchard.v0v2v0.orchard.meta$eval2206$loading__6434__auto____2207.invoke(meta.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.meta$eval2206.invokeStatic(meta.clj:1)
	at cider.inlined_deps.orchard.v0v2v0.orchard.meta$eval2206.invoke(meta.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at cider.nrepl.middleware.ns$eval2185$loading__6434__auto____2186.invoke(ns.clj:1)
	at cider.nrepl.middleware.ns$eval2185.invokeStatic(ns.clj:1)
	at cider.nrepl.middleware.ns$eval2185.invoke(ns.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at cider.nrepl.middleware.track_state$eval2179$loading__6434__auto____2180.invoke(track_state.clj:1)
	at cider.nrepl.middleware.track_state$eval2179.invokeStatic(track_state.clj:1)
	at cider.nrepl.middleware.track_state$eval2179.invoke(track_state.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.nrepl$run_deferred_handler$fn__1504.invoke(nrepl.clj:37)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at cider.nrepl$wrap_tracker$fn__1716.invoke(nrepl.clj:473)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$handle_pprint.invokeStatic(pprint.clj:89)
	at cider.nrepl.middleware.pprint$handle_pprint.invoke(pprint.clj:86)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_pprint$fn__1542.invoke(nrepl.clj:108)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__893.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at cider.nrepl$wrap_test$fn__1700.invoke(nrepl.clj:435)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic(pprint.clj:49)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invoke(pprint.clj:44)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_pprint_fn$fn__1532.invoke(nrepl.clj:89)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__1045.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__694.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1118.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: namespace 'cider.inlined-deps.orchard.v0v2v0.orchard.java' not found
	... 179 more

Also seeing:

2018-05-09 06:00:35,005 ERROR [clojure.tools.nrepl.server] (clojure-agent-send-off-pool-4) Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :session 4c9fc464-dabf-418c-84e2-b7813a23a935, :id 8}: java.lang.ClassNotFoundException: com.sun.javadoc.ClassDoc, compiling:(cider/inlined_deps/orchard/v0v2v0/orchard/
java/parser.clj:1:1)

Doing manual in-ns also fails:

2018-05-09 06:01:10,393 ERROR [clojure.tools.nrepl.server] (clojure-agent-send-off-pool-4) Unhandled REPL handler exception processing message {:ns user, :file *cider-repl 127.0.0.1:XXXX*, :op eval, :column 7, :line 44, :id 21, :code (in-ns 'XX.XX), :content-type true, :session 4c9fc464-dabf-418c-84e2-b7813a23a935}: java.lang.Exception: namespace 'cider.inlined-deps.orchard.v0v2v0.orchard.java' not found, compiling:(cider/inlined_deps/orchard/v0v2v0/orchard/classloader.clj:1:1)

## Steps to reproduce the problem

Connecting to remote nREPL within Immutant, then using cider-repl-set-ns to switch namespace.

Plugins:

  :plugins [[lein-immutant "2.1.0"] [cider/cider-nrepl "0.17.0"]]
  :immutant {:war {:nrepl {:port XXXX}}}

Packaging with lein immutant war --nrepl-start

### CIDER version information

;; CIDER 0.17.0 (Andalucía), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_162

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2018-04-10

### Operating system

Client macOS High Sierra 10.13.4, server Debian 9.

**Comment by bbatsov** [comment]
Seems something's wrong with the inlined dependencies in `cider-nrepl` (orchard in particular), but I can't imagine how can this happen (and why). Your problem is much bigger than one command not working.

**Comment by bbatsov** [comment]
Maybe something to do with https://github.com/clojure-emacs/cider-nrepl#with-jboss-asjboss-eapwildfly ? I've never immutant and that's definitely some weird interaction between it and cider-nrepl.

**Comment by bbatsov** [comment]
I'm closing this ticket due to no recent activity. Feel free to re-open it if you ever come back to it.
