### ISSUE TITLE
cider-0.17 cannot start nREPL

### ISSUE THREAD

**Issue by junjiemars** [clojure-emacs/cider#2298]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*When requesting new features or improvements to existing features you can
discard the template completely. Just make sure to make a good case for your
request.*

**Remove all of the placeholder text in your final report!**

## Expected behavior
start nREPL without existing project.clj, but cider-0.16 version works.

## Actual behavior
Are you sure you want to run `cider-jack-in' without a Clojure project? (y or n) y
Making nrepl-create-client-buffer-function local to *nrepl-server* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server* while let-bound!
Starting nREPL server via clojure -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} cider/cider-nrepl {:mvn/version "0.17.0"}}}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["cider.nrepl/cider-middleware"])'...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Exception in thread "main" java.io.FileNotFoundException: -Sdeps (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at clojure.lang.Compiler.loadFile(Compiler.java:7314)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.lang.Var.invoke(Var.java:519)
	at clojure.lang.AFn.applyToHelper(AFn.java:270)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

error in process sentinel: Could not start nREPL server: Exception in thread "main" java.io.FileNotFoundException: -Sdeps (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at clojure.lang.Compiler.loadFile(Compiler.java:7314)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.lang.Var.invoke(Var.java:519)
	at clojure.lang.AFn.applyToHelper(AFn.java:270)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

## Steps to reproduce the problem
```M-x cider-jack-in```

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information
0.17.0

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
CIDER 0.17
Clojure 1.8.0, Java 1.8.0_152
```

### Lein/Boot version

Lein 2.6.1

### Emacs version

25.3.1

### Operating system

MacOS 10.13.4

**Comment by bbatsov** [comment]
That's because CIDER 0.17 changed the default command it uses to start nREPL outside of a project from `lein` to `clojure`, but for this to work you need Clojure 1.9. 

You can change `cider-default-repl-command` to "lein" to get the old behaviour.

**Comment by junjiemars** [comment]
Thanks, it's just works. 
Before ```cider-jack-in``` a non project nREPL, I should to set ```cider-default-repl-command``` by hand first. To make a backward compatible layer is hard in cider's user Elisp code, so I think it is a compatible bug.

**Comment by bbatsov** [comment]
I'm closing this as it seems no one else has been affected by the change.
