### ISSUE TITLE
might be content-type middleware issue

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2434]
```clojure
(import 'java.util.TimeZone)
(import 'java.text.SimpleDateFormat)

(defn- parse-dt-
  [dt tz_id]
  (let [tz  (java.util.TimeZone/getTimeZone tz_id)
        fmt (doto (java.text.SimpleDateFormat. "EEEEEEEEEEEE, MMMMMMMMMMMM dd, yyyy hh:mm:ss aaa")
              (.setTimeZone tz))]
    {:timestamp (.parse fmt dt)}))

(def tz_id (.getID (java.util.TimeZone/getDefault)))
(def tz (java.util.TimeZone/getTimeZone tz_id))

(parse-dt "Tuesday, November 22, 2016 10:50:09 AM" "UTC")
(parse-dt- "Tuesday, November 22, 2016 10:50:09 AM" tz_id)
```

Execute upper example code with following project definition:

```clojure
(defproject kindle-export-notes "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url  "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [kce-clj "0.1.0"]
                 ;; [candelabrum "0.1.0"]
                 ])
```

If I `lein repl` in project, execute upper code example works fine. But Emacs CIDER jack-in REPL will report error:

    ParseException Unparseable date: "Tuesday, November 22, 2016 10:50:09 AM"  java.text.DateFormat.parse (DateFormat.java:366)

**Comment by stardiviner** [comment]
@bbatsov How to debug this kind of bug (content-type middleware) ?
Also I tried to disable CIDER and clj-refactor inject dependencies:
```elisp
(setq cljr-inject-dependencies-at-jack-in nil)
(setq cider-inject-dependencies-at-jack-in nil)
```

Then I got this stacktrace:

clojure.lang.Compiler$CompilerException: java.text.ParseException: Unparseable date: "Monday, November 21, 2016 5:56:54 AM", compiling:(d2656dc334021881b4d55259de4c9085fb10aa44-init.clj:46:7)
     at clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3700)
        clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3694)
        clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3694)
        clojure.lang.Compiler$DefExpr.eval (Compiler.java:457)
        clojure.lang.Compiler.eval (Compiler.java:7067)
        clojure.lang.Compiler.eval (Compiler.java:7025)
        clojure.core$eval.invokeStatic (core.clj:3206)
        clojure.core$eval.invoke (core.clj:3202)
        clojure.main$repl$read_eval_print__8572$fn__8575.invoke (main.clj:243)
        clojure.main$repl$read_eval_print__8572.invoke (main.clj:243)
        clojure.main$repl$fn__8581.invoke (main.clj:261)
        clojure.main$repl.invokeStatic (main.clj:261)
        clojure.main$repl.doInvoke (main.clj:177)
        clojure.lang.RestFn.invoke (RestFn.java:1523)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1386.invoke (interruptible_eval.clj:87)
        clojure.lang.AFn.applyToHelper (AFn.java:152)
        clojure.lang.AFn.applyTo (AFn.java:144)
        clojure.core$apply.invokeStatic (core.clj:657)
        clojure.core$with_bindings_STAR_.invokeStatic (core.clj:1965)
        clojure.core$with_bindings_STAR_.doInvoke (core.clj:1965)
        clojure.lang.RestFn.invoke (RestFn.java:425)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:85)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:55)
        clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1431$fn__1434.invoke (interruptible_eval.clj:222)
        clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1426.invoke (interruptible_eval.clj:190)
        clojure.lang.AFn.run (AFn.java:22)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
        java.lang.Thread.run (Thread.java:748)
    Caused by: java.text.ParseException: Unparseable date: "Monday, November 21, 2016 5:56:54 AM"
     at java.text.DateFormat.parse (DateFormat.java:366)
        kce_clj.core$parse_dt.invokeStatic (core.clj:44)
        kce_clj.core$parse_dt.invoke (core.clj:39)
        kce_clj.core$parse_meta.invokeStatic (core.clj:51)
        kce_clj.core$parse_meta.invoke (core.clj:47)
        kce_clj.core$parse_entry.invokeStatic (core.clj:57)
        kce_clj.core$parse_entry.invoke (core.clj:53)
        kce_clj.core$lazy_extract$fn__201.invoke (core.clj:66)
        clojure.core$map$fn__5587.invoke (core.clj:2747)
        clojure.lang.LazySeq.sval (LazySeq.java:40)
        clojure.lang.LazySeq.seq (LazySeq.java:49)
        clojure.lang.RT.seq (RT.java:528)
        clojure.core$seq__5124.invokeStatic (core.clj:137)
        clojure.core$dorun.invokeStatic (core.clj:3125)
        clojure.core$doall.invokeStatic (core.clj:3140)
        clojure.core$doall.invoke (core.clj:3140)
        kce_clj.core$extract.invokeStatic (core.clj:71)
        kce_clj.core$extract.invoke (core.clj:68)
        kindle_export_notes.core$read_clips.invokeStatic (d2656dc334021881b4d55259de4c9085fb10aa44-init.clj:12)
        kindle_export_notes.core$read_clips.invoke (d2656dc334021881b4d55259de4c9085fb10aa44-init.clj:9)
        clojure.lang.AFn.applyToHelper (AFn.java:152)
        clojure.lang.AFn.applyTo (AFn.java:144)
        clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3695)
        clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3694)
        clojure.lang.Compiler$InvokeExpr.eval (Compiler.java:3694)
        clojure.lang.Compiler$DefExpr.eval (Compiler.java:457)
        clojure.lang.Compiler.eval (Compiler.java:7067)
        clojure.lang.Compiler.eval (Compiler.java:7025)
        clojure.core$eval.invokeStatic (core.clj:3206)
        clojure.core$eval.invoke (core.clj:3202)
        clojure.main$repl$read_eval_print__8572$fn__8575.invoke (main.clj:243)
        clojure.main$repl$read_eval_print__8572.invoke (main.clj:243)
        clojure.main$repl$fn__8581.invoke (main.clj:261)
        clojure.main$repl.invokeStatic (main.clj:261)
        clojure.main$repl.doInvoke (main.clj:177)
        clojure.lang.RestFn.invoke (RestFn.java:1523)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1386.invoke (interruptible_eval.clj:87)
        clojure.lang.AFn.applyToHelper (AFn.java:152)
        clojure.lang.AFn.applyTo (AFn.java:144)
        clojure.core$apply.invokeStatic (core.clj:657)
        clojure.core$with_bindings_STAR_.invokeStatic (core.clj:1965)
        clojure.core$with_bindings_STAR_.doInvoke (core.clj:1965)
        clojure.lang.RestFn.invoke (RestFn.java:425)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:85)
        clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:55)
        clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1431$fn__1434.invoke (interruptible_eval.clj:222)
        clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1426.invoke (interruptible_eval.clj:190)
        clojure.lang.AFn.run (AFn.java:22)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
        java.lang.Thread.run (Thread.java:748)

**Comment by stardiviner** [comment]
I got different stacktrace when I run command `lein run` in Emacs eshell. (As said before, `lein run` is fine in normal terminal)
```
Exception in thread "main" java.text.ParseException: Unparseable date: "Monday, November 21, 2016 5:56:54 AM", compiling:(core.clj:55:24)
  at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
  at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3694)
  at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3694)
  at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3694)
  at clojure.lang.Compiler$MapExpr.eval(Compiler.java:3047)
  at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
  at clojure.lang.Compiler.eval(Compiler.java:7067)
  at clojure.lang.Compiler.load(Compiler.java:7514)
  at clojure.lang.RT.loadResourceScript(RT.java:379)
  at clojure.lang.RT.loadResourceScript(RT.java:370)
  at clojure.lang.RT.load(RT.java:460)
  at clojure.lang.RT.load(RT.java:426)
  at clojure.core$load$fn__6548.invoke(core.clj:6046)
  at clojure.core$load.invokeStatic(core.clj:6045)
  at clojure.core$load.doInvoke(core.clj:6029)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5848)
  at clojure.core$load_one.invoke(core.clj:5843)
  at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
  at clojure.core$load_lib.invokeStatic(core.clj:5887)
  at clojure.core$load_lib.doInvoke(core.clj:5868)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:659)
  at clojure.core$load_libs.invokeStatic(core.clj:5925)
  at clojure.core$load_libs.doInvoke(core.clj:5909)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:659)
  at clojure.core$require.invokeStatic(core.clj:5947)
  at clojure.core$require.doInvoke(core.clj:5947)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at user$eval148$fn__152.invoke(080ed0e961791538a4154f3d9542d01804cc50f2-init.clj:1)
  at user$eval148.invokeStatic(080ed0e961791538a4154f3d9542d01804cc50f2-init.clj:1)
  at user$eval148.invoke(080ed0e961791538a4154f3d9542d01804cc50f2-init.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:7062)
  at clojure.lang.Compiler.eval(Compiler.java:7052)
  at clojure.lang.Compiler.load(Compiler.java:7514)
  at clojure.lang.Compiler.loadFile(Compiler.java:7452)
  at clojure.main$load_script.invokeStatic(main.clj:278)
  at clojure.main$init_opt.invokeStatic(main.clj:280)
  at clojure.main$init_opt.invoke(main.clj:280)
  at clojure.main$initialize.invokeStatic(main.clj:311)
  at clojure.main$null_opt.invokeStatic(main.clj:345)
  at clojure.main$null_opt.invoke(main.clj:342)
  at clojure.main$main.invokeStatic(main.clj:424)
  at clojure.main$main.doInvoke(main.clj:387)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.lang.Var.applyTo(Var.java:702)
  at clojure.main.main(main.java:37)
Caused by: java.text.ParseException: Unparseable date: "Monday, November 21, 2016 5:56:54 AM"
  at java.text.DateFormat.parse(DateFormat.java:366)
  at kce_clj.core$parse_dt.invokeStatic(core.clj:44)
  at kce_clj.core$parse_dt.invoke(core.clj:39)
  at kce_clj.core$parse_meta.invokeStatic(core.clj:51)
  at kce_clj.core$parse_meta.invoke(core.clj:47)
  at kce_clj.core$parse_entry.invokeStatic(core.clj:57)
  at kce_clj.core$parse_entry.invoke(core.clj:53)
  at kce_clj.core$lazy_extract$fn__209.invoke(core.clj:66)
  at clojure.core$map$fn__5587.invoke(core.clj:2747)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:528)
  at clojure.core$seq__5124.invokeStatic(core.clj:137)
  at clojure.core$dorun.invokeStatic(core.clj:3125)
  at clojure.core$doall.invokeStatic(core.clj:3140)
  at clojure.core$doall.invoke(core.clj:3140)
  at kce_clj.core$extract.invokeStatic(core.clj:71)
  at kce_clj.core$extract.invoke(core.clj:68)
  at kindle_export_notes.core$read_clips.invokeStatic(core.clj:13)
  at kindle_export_notes.core$read_clips.invoke(core.clj:10)
  at clojure.lang.AFn.applyToHelper(AFn.java:152)
  at clojure.lang.AFn.applyTo(AFn.java:144)
  at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
  ... 47 more
```
