### ISSUE TITLE
ClassNotFoundException:SourceLoggingPushbackReader on eval

### ISSUE THREAD

**Issue by birdspider** [clojure-emacs/cider#2490]
Am I the only one who cannot eval ?

## Expected behavior

eval should work
```
C-c C-c (println *clojure-version*)
;; (in repl) {:major 1, :minor 9, :incremental 0, :qualifier nil}
```

## Actual behavior

eval does not work

```
C-c C-c `(println *clojure-version*) ; or any other
```

results in a few seconds lag, then nothing. 

cider repl returns a
```
SCHWERWIEGEND: 
  Unhandled REPL handler exception processing message
    {:ns user, 
     :op eval, 
     :code (println *clojure-version*),
     :file .../emacstest/src/emacstest/core.clj, 
     :line 31, 
     :column 1, 
     :session 5296884f-d21c-4951-a3d5-ef65c158d799,
     :id 11}
Syntax error compiling at 
  (cider/inlined_deps/toolsreader/v1v3v0/clojure/tools/reader.clj:1:1).
 clojure.tools.reader.reader_types.SourceLoggingPushbackReader
 at clojure.lang.Compiler.load(Compiler.java:7643)
...
Caused by: java.lang.ClassNotFoundException: 
  clojure.tools.reader.reader_types.SourceLoggingPushbackReader
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

```

[full stacktrace](https://gist.github.com/birdspider/c80720b41fbd3a78f86e85e35e800dd7)

## Steps to reproduce the problem

eval anything

_I could not find a similar bugreport. I deleted ~/.m2 , ~/.lein/profiles.clj to rule out old deps (tool.reader ?) holding back. The testproject is basicly a `lein new app emacstest` skeleton. 
I'm at a loss at how to investigate further. I also  tried manually calling `cider-eval-defun-at-point`, to no success._

### CIDER version information

```
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.10.0-RC1, Java 1.8.0_181
```

same with

```
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_181
```

or 

```
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.9.0, Java 10.0.2
```

as well as

```
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.10.0-RC1, Java 10.0.2
```

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

I'm using spacemacs. If someone claims that `java.lang.ClassNotFoundException: clojure.tools.reader.reader_types.SourceLoggingPushbackReader` is caused by using spacemacs I will test vanilla-emacs.

### Operating system

Archlinux

**Comment by birdspider** [comment]
oops, it seems that `CIDER 0.18.1snapshot` conj's in `[cider/cider-nrepl "0.19.0-SNAPSHOT"]`, if I force the nrepl to be 0.18.0 via lein `:plugins` it works. 

what to do with the bugreport now ?

**Comment by birdspider** [comment]
I resolved this for me by pinning cider to melpa-stable by adding the following lines
in .spacemacs'  `dotspacemacs/user-init` 

```
(add-to-list 'configuration-layer-elpa-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
```
