### ISSUE TITLE
Printing an error message disables <RET> when sending forms to the REPL

### ISSUE THREAD

**Issue by mathpunk** [clojure-emacs/cider#2501]
## Expected behavior
When an error is printed to the REPL, form-sending behavior is unchanged.

## Actual behavior
If I send a form that causes an error, then afterward, sending functions, last sexp's, or regions will send the text, but they will not execute the command. Instead I need to hop into the REPL window and send the CR manually. 

## Steps to reproduce the problem
I send the sexp `(require '[clojure.java.io :as io)` with `cider-send-last-sexp-to-repl`. Perhaps as a sign of some other problem, I get 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
printed in red. (I think the red might be the problem --- some ansi shenanigan --- but that's speculation based on how it is nigh-impossible to get fish-shell behaving in emacs.) Now sending forms is affected.

## Environment & Version information
CIDER 0.19.0snapshot (package: 20181021.830), nREPL 0.2.12
Clojure 1.9.0, Java 1.8.0_192
I used `cider-jack-in` to start, and I've got leiningen version 2.8.1

### Emacs version
26.1 (Spacemacs)

### Operating system
Manjaro / Arch Linux

**Comment by mathpunk** [comment]
I'm having trouble recreating it myself. If I don't get the behavior again today I will close the issue and blame ghosts. :jack_o_lantern:

**Comment by dpsutton** [comment]
No worries :). Possible in the future someone has this issue and is reassured that it goes away with restarting emacs, or perhaps they pick up the thread of investigation with more insight. If you can't recreate it this is here for the future :)

**Comment by mathpunk** [comment]
New project. Unedited core.clj. I put in a subset of the dependencies I want to work with: 

```
[org.clojure/clojure "1.9.0"]
[clojure.java-time "0.3.2"]
[org.clojure/data.xml "0.0.8"]
```

And had this interaction:

```
;; Clojure 1.9.0, Java 1.8.0_192
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
cyclotron.core> (require '[clojure.java.io :as io])
nil
cyclotron.core>
Nov 05, 2018 9:47:41 AM clojure.tools.logging$eval597$fn__600 invoke
SEVERE: Unhandled REPL handler exception processing message {:op slurp, :url file:/home/man/developing/cyclotron/resources/reports, :session feea35c3-ac59-4c94-ba9f-5d8d0fd9c28c, :id 11}
java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at cider.nrepl.middleware.slurp$slurp_url_to_content_PLUS_body.invokeStatic(slurp.clj:102)
	at cider.nrepl.middleware.slurp$slurp_url_to_content_PLUS_body.invoke(slurp.clj:93)
	at cider.nrepl.middleware.slurp$handle_slurp.invokeStatic(slurp.clj:132)
	at cider.nrepl.middleware.slurp$handle_slurp.invoke(slurp.clj:122)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_slurp$fn__1978.invoke(nrepl.clj:151)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at cider.nrepl$wrap_undef$fn__2142.invoke(nrepl.clj:501)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at cider.nrepl$wrap_tracker$fn__2134.invoke(nrepl.clj:490)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at cider.nrepl$wrap_macroexpand$fn__2054.invoke(nrepl.clj:297)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__1255.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__2078.invoke(nrepl.clj:351)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__904.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1328.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 (io/resource "reports")
```
Turns out I can still send other forms to the repl. But still, this does remind me of something that was nagging me--- do file objects automatically get slurped for the repl or something? I recall seeing the full text of some files I've worked with when I just expected to see them as a file object.

**Comment by mathpunk** [comment]
`io/file`, `io/as-file`, `io/resource`.... These all choke when given a path that is to a directory.

**Comment by mathpunk** [comment]
A tiny bit more insight: I just printed too much text to the repl, but not so much that I crashed emacs. I'm experiencing the same issue, where sending a form to the repl does send the form, but doesn't execute it --- there's no CR sent, or something. But this time, I thought to look at the `*Messages*` buffer, and saw this:

```
Indenting region...done
Indenting region...done
auto trimmed 4 chars
Indenting region...done
Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. [4 times]
Auto-saving...
Indenting region...
lisp-indent-line: Text is read-only
Mark set
Indenting region...done
, ESC is undefined
Indenting region...
lisp-indent-line: Text is read-only
Mark set
Indenting region...
lisp-indent-line: Text is read-only
```
That is, before things are broken, there are `Indenting region...done` messages, but after sending forms breaks, instead there are `Indenting region...lisp-indent-line: Text is read-only`.

**Comment by mathpunk** [comment]
I've learned that there's a difference between a buffer being read-only, and a region of text being read-only. The next time I catch this error, I will try using some of this elisp code to try and resume sending forms to the repl without restarting. Leaving it here in case someone else is having a similar problem: https://stackoverflow.com/questions/24565068/emacs-text-is-read-only/30906336#30906336

**Comment by bbatsov** [comment]
The slurp-related errors are coming from some bug in the `content-type` middleware. You can disable it like this `(setq cider-repl-use-content-types nil)`.
