### ISSUE TITLE
cider-jack-in fails

### ISSUE THREAD

**Issue by edvorg** [clojure-emacs/cider#2549]
cider-jack-in command hangs and then fails.

## Expected behavior

cider-jack-in should jack in

## Actual behavior

hangs for some time and then fails with following log

```
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Warning: implicit middleware found: refactor-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-apropos, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-classpath, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-complete, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-debug, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-enlighten, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-format, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-info, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-inspect, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-macroexpand, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-ns, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-out, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-content-type, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint-fn, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-profile, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-refresh, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-resource, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-spec, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-stacktrace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-test, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-trace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-tracker, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-undef, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-version, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'refactor-nrepl.middleware/wrap-refactor, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-apropos, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-classpath, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-complete, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-debug, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-enlighten, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-format, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-info, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-inspect, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-macroexpand, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-ns, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-out, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-content-type, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint-fn, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-profile, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-refresh, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-resource, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-spec, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-stacktrace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-test, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-trace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-tracker, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-undef, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-version, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'refactor-nrepl.middleware/wrap-refactor, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-apropos, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-classpath, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-complete, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-debug, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-enlighten, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-format, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-info, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-inspect, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-macroexpand, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-ns, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-out, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-content-type, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint-fn, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-profile, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-refresh, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-resource, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-spec, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-stacktrace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-test, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-trace, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-tracker, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-undef, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-version, see nrepl.middleware/set-descriptor!
nREPL server started on port 38431 on host :: - nrepl://:::38431
ERROR: Unhandled REPL handler exception processing message {:op clone, :id 1}
java.lang.NullPointerException
	at clojure.core$deref_future.invokeStatic(core.clj:2292)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at cider.piggieback$wrap_cljs_repl$fn__22756.invoke(piggieback.clj:301)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_format$fn__23142.invoke(nrepl.clj:222)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_content_type$fn__23084.invoke(nrepl.clj:139)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_tracker$fn__23248.invoke(nrepl.clj:484)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_slurp$fn__23092.invoke(nrepl.clj:150)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at refactor_nrepl.middleware$wrap_refactor$fn__27980.invoke(middleware.clj:214)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_resource$fn__23208.invoke(nrepl.clj:408)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_ns$fn__23176.invoke(nrepl.clj:308)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_spec$fn__23216.invoke(nrepl.clj:420)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_version$fn__23264.invoke(nrepl.clj:503)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_out$fn__23184.invoke(nrepl.clj:336)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_enlighten$fn__23134.invoke(nrepl.clj:218)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic(pprint.clj:61)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invoke(pprint.clj:56)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_pprint_fn$fn__23064.invoke(nrepl.clj:100)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_apropos$fn__23100.invoke(nrepl.clj:158)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_undef$fn__23256.invoke(nrepl.clj:495)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_pprint$fn__23074.invoke(nrepl.clj:119)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_trace$fn__23240.invoke(nrepl.clj:466)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_debug$fn__23126.invoke(nrepl.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_inspect$fn__23160.invoke(nrepl.clj:255)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_refresh$fn__23200.invoke(nrepl.clj:382)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_classpath$fn__23108.invoke(nrepl.clj:166)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_info$fn__23150.invoke(nrepl.clj:236)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_test$fn__23232.invoke(nrepl.clj:446)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_stacktrace$fn__23224.invoke(nrepl.clj:436)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__23192.invoke(nrepl.clj:345)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17873.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__22344.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

## Steps to reproduce the problem

create new project with contents of attached project.clj, issue cider-jack-in command.

project.clj

```clojure
(defproject hello-world "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url  "http://www.eclipse.org/legal/epl-v10.html"}

  :min-lein-version "2.7.1"

  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.238"]
                 [org.clojure/core.async  "0.4.474"]
                 [reagent "0.7.0"]]

  :plugins [[lein-figwheel "0.5.16"]
            [lein-cljsbuild "1.1.7" :exclusions [[org.clojure/clojure]]]]

  :source-paths ["src"]

  :cljsbuild {:builds
              [{:id           "dev"
                :source-paths ["src"]
                :figwheel {:on-jsload "hello-world.core/on-js-reload"
                           :open-urls ["http://localhost:3449/index.html"]}

                :compiler {:main                 hello-world.core
                           :asset-path           "js/compiled/out"
                           :output-to            "resources/public/js/compiled/hello_world.js"
                           :output-dir           "resources/public/js/compiled/out"
                           :source-map-timestamp true
                           :preloads             [devtools.preload]}}
               {:id           "min"
                :source-paths ["src"]
                :compiler     {:output-to     "resources/public/js/compiled/hello_world.js"
                               :main          hello-world.core
                               :optimizations :advanced
                               :pretty-print  false}}]}

  :figwheel {:css-dirs ["resources/public/css"]}

  :profiles {:dev {:dependencies  [[binaryage/devtools "0.9.9"]
                                   [figwheel-sidecar "0.5.16"]
                                   [cider/piggieback "0.3.10"]]
                   :source-paths  ["src" "dev"]
                   :repl-options  {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}
                   :clean-targets ^{:protect false} ["resources/public/js/compiled"
                                                     :target-path]}})

```

### CIDER version information

Cider is unable to launch, cider plugin version 0.18.0, toolsnrepl 0.2.13, refactor nrepl 2.4.0

### Lein/Boot version

Lein 2.8.3

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)

### Operating system

Linux Manjaro

**Comment by bbatsov** [comment]
See
https://nrepl.org/nrepl/troubleshooting.html. If I had to guess I’d bet on
your version of figwheel-sidecar.

**Comment by edvorg** [comment]
DId ancient upgrade to everything in the project and it seems to solve the issue, not sure what was the root of the problem, but figwheel-sidecar was outdated indeed.

**Comment by bbatsov** [comment]
Great!
