### ISSUE TITLE
cider-debug: "nrepl-send-sync-request timing out" with cider-inspect-last-result during debug

### ISSUE THREAD

**Issue by R1ck77** [clojure-emacs/cider#2566]
Hi!

While I'm using cider with great satisfaction since a while, I just started debugging Clojure with cider, so I apologize in advance for any naivety on my side. 

Thank you all your work so far!

## Summary

When I print a very long expression in while debugging the output is truncated.

I try to use ``cider-inspect-last-result`` to see the rest, but the command doesn't produce anything useful (the ``print`` command seems to work anyway).

## Steps to reproduce

Create a very simple Leiningen project with this source:

    (ns cider-debug-bug.core
      (:gen-class))
    
    (defn long-stuff []
      (repeatedly 1000 #(identity 42) ))
    
    (defn get-long-stuff []
      (let [x (long-stuff)]
       #dbg (take 10 x)))
    
``cider-jack-in-clj`` and I get this header:

    ;; Connected to nREPL server - nrepl://localhost:42761
    ;; CIDER 0.20.0snapshot (package: 20190108.925), nREPL 0.5.3
    ;; Clojure 1.9.0, Java 1.8.0_60
    [...]

I also tried with CIDER 0.19.0 (Raleigh).

``cider-load-buffer`` in the source file.

``C-M-x`` on ``get-long-stuff`` (evaluated correctly)

``(get-long-stuff)`` in the repl [debugging ``get-long-stuff`` now]

``e x`` and I get something like:

    #dbg (take 10 x))) => (42 42 42 42 42 42 42 42 42 42 ...)
    
``M-x cider-inspect-last-result``

### Actual result

Emacs stalls for 5-10 seconds and I get the following message:

    nrepl-send-sync-request: Sync nREPL request timed out (ns cider-debug-bug.core op eval code *1 inspect true page-size 32)

Nothing apparently changes in the ``core.clj`` buffer or elsewhere.

### Expected result

No error and some kind of output or view of my data.

## More info

**OS**

    Ubuntu 18.04.1 LTS

**Emacs**

    GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
    
**Leiningen version**

    Leiningen 2.8.3 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
    
with the following profile.clj:

    {
     :repl  {:dependencies  [[nrepl/nrepl "0.5.3"]] }
    }

    
**CIDER**

    CIDER 0.20.0snapshot (package: 20190108.925)
    
with header:
    
    ;; Connected to nREPL server - nrepl://localhost:42761
    ;; CIDER 0.20.0snapshot (package: 20190108.925), nREPL 0.5.3

but the same happens with:

    ;; Connected to nREPL server - nrepl://localhost:45053
    ;; CIDER 0.19.0 (Raleigh), nREPL 0.5.3

**Clojure**

    ;; Clojure 1.9.0, Java 1.8.0_60

(the same behavior happened in my project with Clojure 1.8.0 though).

## More more info (possibly too much of it)

As a side note, I admit the debugger is not really behaving: *I started using it today* so again, it's probably all my fault, but I had little luck with it overall.

Among the things that **seem** to happen (stress on "seem" because I'm *very possibly messing up*):

- I get a nasty ``Unable to resolve symbol: STATE__ in this context`` during some code evaluation.

This is the minimal example:

    (defn y-tho? []
      (fn [{counter :counter}]
        #dbg {:counter (inc counter)}))

(this seem to happen only since I updated CIDER: works fine on 0.18.1snapshot)

- I can't load a namespace the first time with ``cider-load-buffer`` *in my regular project* (the small demo works fine) when it contains a ``#break`` or a ``#dbg``.

I get this:

    [nREPL] Starting server via /home/dimeo/bin/lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.20.0-SNAPSHOT\"\] -- repl :headless :host localhost...
    error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Warning: implicit middleware found: cider-nrepl.plugin/middleware
    Please declare all middleware in :middleware as implicit loading is deprecated.
    Compiling cjscene.scene.dummy-scene
    java.lang.IllegalStateException: Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader, compiling:(cjscene/scene/dummy_scene.clj:160:100)
    Exception in thread "main" java.lang.IllegalStateException: Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader, compiling:(cjscene/scene/dummy_scene.clj:160:100)
            at clojure.lang.Compiler.compile(Compiler.java:7639)
            at clojure.lang.RT.compile(RT.java:406)
            at clojure.lang.RT.load(RT.java:451)
            at clojure.lang.RT.load(RT.java:419)
            [OMISSIS]
    Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader
            at clojure.lang.Var$Unbound.throwArity(Var.java:43)
            at clojure.lang.AFn.invoke(AFn.java:32)
            at clojure.lang.Var.invoke(Var.java:379)
            at clojure.lang.LispReader$CtorReader.readTagged(LispReader.java:1249)
            at clojure.lang.LispReader$CtorReader.invoke(LispReader.java:1228)
            at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:684)
            at clojure.lang.LispReader.read(LispReader.java:263)
            at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
            at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
            at clojure.lang.LispReader.read(LispReader.java:263)
            at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
            at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
            at clojure.lang.LispReader.read(LispReader.java:263)
            at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
            at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
            at clojure.lang.LispReader.read(LispReader.java:263)
            at clojure.lang.LispReader.read(LispReader.java:196)
            at clojure.lang.Compiler.compile(Compiler.java:7537)
            ... 32 more
    Compilation failed: Subprocess failed
    
In order to eval the file I need to:

- remove all explicit ``#dbg`` and ``#break``
- eval the file
- set the ``#dbg`` and ``#break`` again, and only then eval

Needless to say, I'm not having this great of a time... :smile:

<hr/>

Sorry for the wall of text.

Given the number of problems I'm facing I would put my money on a nasty local configuration problem (aka *all my fault*), even though I ran through the Troubleshooting section of the manual already and I don't know where to bang my head.

Thank for your attention and for any help you can provide!

**Comment by R1ck77** [comment]
After a night of sleep, I figured that there are no reasons to waste anybody's time on something that may be a problem on my end. I'll figure things better out and then I'll possibly reopen if still relevant.
