### ISSUE TITLE
Failing when starting nREPL

### ISSUE THREAD

**Issue by sreeramvenkat** [clojure-emacs/cider#2569]
### Scenario

Tried starting the the nREPL  by M-x cider-jack-in

### Error Encountered

Error loading nrepl.server: java.lang.RuntimeException: Unable to resolve symbol: uuid in this context, compiling:(nrepl/transport.clj:126)

### Environment & Version information

cider 0.20.0
Leiningen 2.8.3 on Java 1.8.0_121 Java HotSpot(TM) Server VM
GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8)
Linux 3.13.0-37-generic #64-Ubuntu SMP

### Full error message taken from *Messages* after M-x cider-jack-in

[nREPL] Starting server via /home/sreeram/installs/leiningen/lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.20.0\"\] -- repl :headless :host localhost...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Warning: cider-nrepl requires Clojure 1.8 or greater.
Warning: cider-nrepl will not be included in your project.
Warning: cider-nrepl requires Clojure 1.8 or greater.
Warning: cider-nrepl will not be included in your project.
Error loading nrepl.server: java.lang.RuntimeException: Unable to resolve symbol: uuid in this context, compiling:(nrepl/transport.clj:126)
Exception in thread "main" java.lang.RuntimeException: No such var: nrepl.server/start-server, compiling:(/tmp/form-init4474438570696418557.clj:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6235)
	at clojure.lang.Compiler.analyze(Compiler.java:6177)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3452)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6411)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.access$100(Compiler.java:37)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5837)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6409)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.analyze(Compiler.java:6177)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5572)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5008)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3629)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6407)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.eval(Compiler.java:6462)
	at clojure.lang.Compiler.eval(Compiler.java:6455)
	at clojure.lang.Compiler.load(Compiler.java:6902)
	at clojure.lang.Compiler.loadFile(Compiler.java:6863)
	at clojure.main$load_script.invoke(main.clj:282)
	at clojure.main$init_opt.invoke(main.clj:287)
	at clojure.main$initialize.invoke(main.clj:315)
	at clojure.main$null_opt.invoke(main.clj:348)
	at clojure.main$main.doInvoke(main.clj:426)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:405)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:518)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: nrepl.server/start-server
	at clojure.lang.Util.runtimeException(Util.java:156)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6694)
	at clojure.lang.Compiler.resolve(Compiler.java:6664)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6625)
	at clojure.lang.Compiler.analyze(Compiler.java:6198)
	... 28 more
Subprocess failed

error in process sentinel: Could not start nREPL server: Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Warning: cider-nrepl requires Clojure 1.8 or greater.
Warning: cider-nrepl will not be included in your project.
Warning: cider-nrepl requires Clojure 1.8 or greater.
Warning: cider-nrepl will not be included in your project.
Error loading nrepl.server: java.lang.RuntimeException: Unable to resolve symbol: uuid in this context, compiling:(nrepl/transport.clj:126)
Exception in thread "main" java.lang.RuntimeException: No such var: nrepl.server/start-server, compiling:(/tmp/form-init4474438570696418557.clj:1)
	at clojure.lang.Compiler.analyze(Compiler.java:6235)
	at clojure.lang.Compiler.analyze(Compiler.java:6177)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3452)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6411)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.access$100(Compiler.java:37)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5837)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6409)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.analyze(Compiler.java:6177)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5572)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5008)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3629)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6407)
	at clojure.lang.Compiler.analyze(Compiler.java:6216)
	at clojure.lang.Compiler.eval(Compiler.java:6462)
	at clojure.lang.Compiler.eval(Compiler.java:6455)
	at clojure.lang.Compiler.load(Compiler.java:6902)
	at clojure.lang.Compiler.loadFile(Compiler.java:6863)
	at clojure.main$load_script.invoke(main.clj:282)
	at clojure.main$init_opt.invoke(main.clj:287)
	at clojure.main$initialize.invoke(main.clj:315)
	at clojure.main$null_opt.invoke(main.clj:348)
	at clojure.main$main.doInvoke(main.clj:426)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:405)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:518)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: nrepl.server/start-server
	at clojure.lang.Util.runtimeException(Util.java:156)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6694)
	at clojure.lang.Compiler.resolve(Compiler.java:6664)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6625)
	at clojure.lang.Compiler.analyze(Compiler.java:6198)
	... 28 more
Subprocess failed

**Comment by bbatsov** [comment]
Seems your project is using Clojure 1.7 or older. As you can see in the warnings, cider-nREPL requires Clojure 1.8 or newer.

**Comment by sreeramvenkat** [comment]
Thanks @bbatsov . I had incorrect Clojure version as a dependency and modifying that fixed the issue.
