### ISSUE TITLE
cider-jack-in hangs and then fails

### ISSUE THREAD

**Issue by kirang89** [clojure-emacs/cider#2758]
## Expected behavior

`M-x cider-jack-in` should setup a REPL without any errors

## Actual behavior

`cider-jack-in` hangs and then displays the following error:

```
ERROR: Unhandled REPL handler exception processing message {:op version, :prefix-rewriting false, :debug false, :session 34da9afe-3755-4942-83ae-2420d2a7f392, :id 8}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'clojure.tools.nrepl.transport/Transport found for class: nrepl.transport.FnTransport
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.tools.nrepl.transport$eval17852$fn__17853$G__17843__17860.invoke(transport.clj:16)
	at refactor_nrepl.middleware$version_reply.invokeStatic(middleware.clj:144)
	at refactor_nrepl.middleware$version_reply.invoke(middleware.clj:143)
	at refactor_nrepl.middleware$wrap_refactor$fn__29717.invoke(middleware.clj:212)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__18122.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__24233.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The `nrepl` log:
```
[nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.5.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.23.0-SNAPSHOT\"\] -- repl :headless :host localhost
```

## Steps to reproduce the problem

- Open a clojure project
- `M-x cider-jack-in`

### CIDER version information

```
;; CIDER 0.24.0snapshot, nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_144
```

### Lein/Boot version

```
Leiningen 2.9.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM
```

### Emacs version

```
GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-04-13
```

### Operating system
```
OS X 10.14.6 Mojave
```

**Comment by bbatsov** [comment]
Judging by this line:

> 	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__18122.invoke(middleware.clj:22)

you have some dep that relies on the legacy tools.nrepl server. Once you update it everything will work just fine.

**Comment by kirang89** [comment]
There indeed was a dependency that was pulling in `[org.clojure/tools.nrepl "0.2.12"]`. Excluding this from that dep, seems to have fixed this issue. Thanks for the prompt response! :)

**Comment by jdf-id-au** [comment]
I got something superficially similar to this and https://github.com/clojure-emacs/cider/issues/2582 seemingly as a result of somehow having a stale project `classes/` directory. (Maybe something to do with my project build process and the fact that I depended on nrepl and cider-nrepl...). Fixed by nuking said directory 😄 

```
Exception in thread "nREPL-session-0725bc9e-40ab-420b-ad1f-1b2d40f2dd70" java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: nrepl.middleware.caught$caught_transport$reify__29022
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:584)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:576)
	at nrepl.transport$eval2343$fn__2361$G__2334__2368.invoke(transport.clj:24)
	at nrepl.middleware.interruptible_eval$evaluate$fn__2596.invoke(interruptible_eval.clj:147)
	at clojure.main$repl$fn__9215.invoke(main.clj:460)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:99)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:71)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__2604$fn__2608.invoke(interruptible_eval.clj:166)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__2676$fn__2680.invoke(session.clj:236)
	at nrepl.middleware.session$session_exec$main_loop__2676.invoke(session.clj:235)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
