### ISSUE TITLE
Cider-nrepl got connected apparently okay but it does not work.

### ISSUE THREAD

**Issue by touxstone** [clojure-emacs/cider#2872]
Hi, group, I would appreciate any help on this issue please, my emacs/cider got connected as expected,  apparently, but it does not work when at evaluating code on any `clj buffer` or the `cider-nrepl` itself.

## Expected behavior
Once the nrepl on EMACS starts I test it e.g. evaluating
```
user> (+ 4 5)
;; => 9
``` 
## Actual behavior
This is the output I got:
```
ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/buffer-size 4096, :ns test2.core, :file *cider-repl test01072020/test2:localhost:45837(clj)*, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :op eval, :column 13, :line 44, :id 8, :code (+ 4 5), :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/options {:right-margin 70}, :session 7eea49d6-398b-4341-ae3a-8412a7c249db}
Syntax error macroexpanding at (track_state.clj:157:8).
at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3707)
at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
at clojure.lang.Compiler.eval(Compiler.java:7182)
at clojure.lang.Compiler.load(Compiler.java:7636)
at clojure.lang.RT.loadResourceScript(RT.java:381)
at clojure.lang.RT.loadResourceScript(RT.java:372)
at clojure.lang.RT.load(RT.java:459)
at clojure.lang.RT.load(RT.java:424)
at clojure.core$load$fn__6839.invoke(core.clj:6126)
at clojure.core$load.invokeStatic(core.clj:6125)
at clojure.core$load.doInvoke(core.clj:6109)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at clojure.core$load_one.invokeStatic(core.clj:5908)
at clojure.core$load_one.invoke(core.clj:5903)
at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
at clojure.core$load_lib.invokeStatic(core.clj:5947)
at clojure.core$load_lib.doInvoke(core.clj:5928)
at clojure.lang.RestFn.applyTo(RestFn.java:142)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$load_libs.invokeStatic(core.clj:5985)
at clojure.core$load_libs.doInvoke(core.clj:5969)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$require.invokeStatic(core.clj:6007)
at clojure.core$require.doInvoke(core.clj:6007)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at cider.nrepl$run_deferred_handler$fn__2051.invoke(nrepl.clj:53)
at clojure.lang.Delay.deref(Delay.java:42)
at clojure.core$deref.invokeStatic(core.clj:2320)
at clojure.core$deref.invoke(core.clj:2306)
at cider.nrepl$wrap_tracker$fn__2241.invoke(nrepl.clj:460)
at nrepl.middleware$wrap_conj_descriptor$fn__661.invoke(middleware.clj:16)
at nrepl.middleware.session$session$fn__1094.invoke(session.clj:309)
at nrepl.middleware$wrap_conj_descriptor$fn__661.invoke(middleware.clj:16)
at cider.nrepl$wrap_xref$fn__2267.invoke(nrepl.clj:489)
at nrepl.middleware$wrap_conj_descriptor$fn__661.invoke(middleware.clj:16)
at nrepl.server$default_handler$fn__1618.invoke(server.clj:130)
at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
at nrepl.server$handle_STAR_.invoke(server.clj:19)
at nrepl.server$handle$fn__1589.invoke(server.clj:39)
at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
at clojure.lang.AFn.call(AFn.java:18)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-0.fc30.x86_64/jre/lib/ext/java-atk-wrapper.jar (No such file or directory)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:225)
at java.util.zip.ZipFile.<init>(ZipFile.java:155)
at java.util.jar.JarFile.<init>(JarFile.java:166)
at java.util.jar.JarFile.<init>(JarFile.java:130)
at cider.nrepl.middleware.track_state$fn__6142.invokeStatic(track_state.clj:155)
at cider.nrepl.middleware.track_state$fn__6142.invoke(track_state.clj:155)
at clojure.core$map$fn__5866.invoke(core.clj:2755)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.RT.seq(RT.java:535)
at clojure.core$seq__5402.invokeStatic(core.clj:137)
at clojure.core$map$fn__5866.invoke(core.clj:2746)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.Cons.next(Cons.java:39)
at clojure.lang.RT.next(RT.java:713)
at clojure.core$next__5386.invokeStatic(core.clj:64)
at clojure.core$concat$cat__5495$fn__5496.invoke(core.clj:742)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:58)
at clojure.lang.Cons.next(Cons.java:39)
at clojure.lang.RT.next(RT.java:713)
at clojure.core$next__5386.invokeStatic(core.clj:64)
at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:169)
at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
at clojure.core$reduce.invokeStatic(core.clj:6828)
at clojure.core$into.invokeStatic(core.clj:6895)
at clojure.core$into.invoke(core.clj:6887)
at clojure.lang.AFn.applyToHelper(AFn.java:156)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3702)
... 45 more

```

## Steps to reproduce the problem
I also removed references to nrepl in the dependencies part on `~/.lein/profiles.clj` as I read on that setting was not needed anymore from some cider versions ago.

```
{:repl {:plugins [[lein-try "0.4.3"]
                  [lein-ancient "0.6.15"]]
:dependencies []}}

```
### CIDER version information
```
CIDER 0.26.0snapshot (package: 20200629.944)
```
This the output I got when start cider on a `clj buffer`
```
[nREPL] Starting server via /home/txarly/bin/lein update-in :dependencies conj \[nrepl\ \"0.8.0-alpha3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.25.3-SNAPSHOT\"\] -- repl :headless :host localhost
[nREPL] server started on 45837
[nREPL] Establishing direct connection to localhost:45837 ...
[nREPL] Direct connection to localhost:45837 established
```

### Lein/Boot version

```
Leiningen 2.9.3 on Java 1.8.0_252 OpenJDK 64-Bit Server VM
```
### Emacs version

GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.11) of 2019-12-10

### Operating system
Operating System: Fedora 30 (Thirty)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.6.13-100.fc30.x86_64
      Architecture: x86-64

**Comment by bbatsov** [comment]
Seems that something's missing in the JDK:

> Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-0.fc30.x86_64/jre/lib/ext/java-atk-wrapper.jar (No such file or directory)

I'm guessing switching to some newer JDK will fix the problem, but I'm surprised you're experiencing this in the first place.

**Comment by touxstone** [comment]
I found a solution by, yep, changing the java version to work on by using the following command: 
```
# alternatives --config java
```
I found out I had another more so chose the latest I had already installed: `Java 11.0.7 OpenJDK 64-Bit Server VM`
So now my `$ lein -v` reads: `Leiningen 2.9.3 on Java 11.0.7 OpenJDK 64-Bit Server VM` and CLOJURE-EMACS CIDER goes OK ~~`. 
Now I have to find a gentle tutorial to play with web apps and so on, thank you.

**Comment by Bost** [comment]
> Seems that something's missing in the JDK:
> 
> > Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-0.fc30.x86_64/jre/lib/ext/java-atk-wrapper.jar (No such file or directory)
> 
> I'm guessing switching to some newer JDK will fix the problem, but I'm surprised you're experiencing this in the first place.

Interestingly enough on GuixOS in on one of my projects everything works under openjdk 17.0.1 but under openjdk18 I get:
```
$ java --version 
openjdk 18 2022-03-22
OpenJDK Runtime Environment (build 18+0-adhoc..source)
OpenJDK 64-Bit Server VM (build 18+0-adhoc..source, mixed mode, sharing)

$ clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0"} refactor-nrepl/refactor-nrepl {:mvn/version "3.5.2"} cider/cider-nrepl {:mvn/version "0.28.3"}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'
WARNING: Implicit use of clojure.main with options is deprecated, use -M
nREPL server started on port 44465 on host localhost - nrepl://localhost:44465
ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 80}, :op init-debugger, :session f1f43d01-0cda-4e31-946a-6478d68d065f, :id 6}
Syntax error macroexpanding at (cider/nrepl/inlined_deps/orchard/v0v9v2/orchard/java/parser.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7665)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3714)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6151)
	at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2741)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7199)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4350$loading__6789__auto____4351.invoke(info.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4350.invokeStatic(info.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4350.invoke(info.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:930)
	at cider.nrepl.middleware.stacktrace$eval4259$loading__6789__auto____4260.invoke(stacktrace.clj:1)
	at cider.nrepl.middleware.stacktrace$eval4259.invokeStatic(stacktrace.clj:1)
	at cider.nrepl.middleware.stacktrace$eval4259.invoke(stacktrace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at cider.nrepl.middleware.debug$eval3867$loading__6789__auto____3868.invoke(debug.clj:1)
	at cider.nrepl.middleware.debug$eval3867.invokeStatic(debug.clj:1)
	at cider.nrepl.middleware.debug$eval3867.invoke(debug.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.nrepl$handler_future$fn__3138$fn__3139.invoke(nrepl.clj:53)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at cider.nrepl$handler_future$fn__3138.invoke(nrepl.clj:52)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at cider.nrepl$wrap_debug$fn__3221.invoke(nrepl.clj:163)
	at nrepl.middleware$wrap_conj_descriptor$fn__942.invoke(middleware.clj:16)
	at cider.nrepl$wrap_inspect$fn__3255.invoke(nrepl.clj:227)
	at nrepl.middleware$wrap_conj_descriptor$fn__942.invoke(middleware.clj:16)
	at nrepl.middleware.session$add_stdin$fn__1396.invoke(session.clj:379)
	at nrepl.middleware$wrap_conj_descriptor$fn__942.invoke(middleware.clj:16)
	at 
```

**Comment by vemv** [comment]
I believe your stacktrace is incomplete. There should be a second section saying `Caused by:`

**Comment by Bost** [comment]
> I believe your stacktrace is incomplete. There should be a second section saying `Caused by:`

Ah sorry. I fixed that in my previous comment.

**Comment by vemv** [comment]
Thanks! Can you create an isolated issue in https://github.com/clojure-emacs/orchard ?
