### ISSUE TITLE
cider-jack-in-cljs starts repl but all forms entered hang

### ISSUE THREAD

**Issue by ergodicbreak** [clojure-emacs/cider#3266]
## Expected Behavior

With point in cljs file, cider-jack-in-cljs starts repl, evaluating a form like (+ 1 1) prints a result.

## Actual behavior

The repl starts OK (choosing browser type), the browser launches with default cljs page, but eval of (+ 1 1) hangs; in the modeline there is a progress meter like (===....) that keeps running. Pressing returns another prompt and the progress meter keeps running.

Note that cider-jack-in from a clj file works OK.

Starting a CLI cljs repl produces an error which may be the issue, but I don't understand what's causing it; the CLI repl itself works though. However I only got this error on one session, quitting and restarting I didn't get the error. Log of the error below:

```
lucretius:~/work/living_clojure/cheshire-cat$ clj -M -m cljs.main -ro "{:launch-browser false}" -w src/cljs -c cheshire-cat.co
re -r -p 3000
Waiting for browser to connect to http://localhost:9000 ...
ClojureScript 1.11.54
cljs.user=> Exception in thread "Thread-118" java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
	at cljs.repl.server$send_and_close.invokeStatic(server.clj:168)
	at cljs.repl.server$send_and_close.invoke(server.clj:144)
	at cljs.repl.browser$send_static.invokeStatic(browser.clj:208)
	at cljs.repl.browser$send_static.invoke(browser.clj:181)
	at cljs.repl.server$dispatch_request.invokeStatic(server.clj:192)
	at cljs.repl.server$dispatch_request.invoke(server.clj:182)
	at cljs.repl.server$handle_connection.invokeStatic(server.clj:206)
	at cljs.repl.server$handle_connection.invoke(server.clj:202)
	at cljs.repl.server$server_loop$fn__8790.invoke(server.clj:216)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
Watch compilation log available at: out/watch.log

cljs.user=> (+ 1 1)
2
cljs.user=> 
```

## Steps to reproduce the problem

cider-jack-in-cljs from a cljs file, choose browser type. (+ 1 1) at the prompt and press enter.

### CIDER version information

;; CIDER 1.6.0-snapshot (package: 20221026.1100), nREPL 1.0.0
;; Clojure 1.11.1, Java 17.0.5

### Lein / Clojure CLI version

lucretius:~/work/living_clojure/cheshire-cat$ clj --version
Clojure CLI version 1.11.1.1182

### Emacs version

GNU Emacs 28.1 (build 1, x86_64-alpine-linux-musl, GTK+ Version 3.24.33, cairo version 1.17.4) of 2022-05-18

### Operating system

Alpine

### JDK distribution

lucretius:~/work/living_clojure/cheshire-cat$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-alpine-r0)
OpenJDK 64-Bit Server VM (build 17.0.5+8-alpine-r0, mixed mode, sharing)

**Comment by ergodicbreak** [comment]
After a few restarts with the CLI, now for some reason the cider session works. When in doubt, reboot I guess.
