### ISSUE TITLE
`cider-jack-in` fails reporting a syntax error in macroexpanding

### ISSUE THREAD

**Issue by khinsen** [clojure-emacs/cider#3339]
## Expected behavior

`M-x cider-jack-in` should start a working nREPL in an Emacs buffer

## Actual behavior

The nREPL is started, but CIDER fails to connect to it. The error message is
```
ERROR: Unhandled REPL handler exception processing message {:op init-debugger, :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 70}, :session 0f51e222-e103-400d-9d06-5a401407a24d, :id 6}
Syntax error macroexpanding at (cider/nrepl/inlined/deps/orchard/v0v11v0/orchard/java/parser.clj:1:1).
```
followed by a lengthy stack trace.

Note: I tried the same with a real Clojure project, thus with a non-empty `deps.edn`. The initial part of the error message is then different, but there is always the "syntax error macroexpanding", with the same location reference `cider/nrepl/inlined/deps/orchard/v0v11v0/orchard/java/parser.clj:1:1`.

## Steps to reproduce the problem

- Create an empty directory
- Create `deps.edn` containing just `{}` (i.e. no dependencies)
- Open `deps.edn` in Emacs.
- `M-x cider-jack-in`.

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:45437
;; CIDER 1.7.0 (Côte d'Azur), nREPL 1.0.0
;; Clojure 1.11.1, Java 19.0.1
```

### Lein / Clojure CLI version

Clojure CLI 1.11.1.1165

### Emacs version

28.2

### Operating system

Ubuntu 20.04 plus the Guix package manager  
Emacs, CIDER, openjdk, clojure, clojure-tools installed via Guix (commit 0c6a7e1045cbd06336ef3699734a803a2e4038e5)

### JDK distribution

```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
```

**Comment by khinsen** [comment]
And here is the `nrepl-message` log:
```
(-->
  id         "1"
  op         "clone"
  time-stamp "2023-05-05 20:47:09.333923472"
)
(<--
  id          "1"
  session     "a7b029f6-9e2c-447c-9166-ecfdd8840d52"
  time-stamp  "2023-05-05 20:47:09.344799628"
  new-session "24fb3ff6-b603-402e-909f-713faa1812d9"
  status      ("done")
)
(-->
  id         "2"
  op         "clone"
  time-stamp "2023-05-05 20:47:09.365036711"
)
(<--
  id          "2"
  session     "63936f4e-8a9d-4325-a7fc-248d24a6818a"
  time-stamp  "2023-05-05 20:47:09.367407509"
  new-session "44d025b7-1a3f-44ab-8624-8b233436d455"
  status      ("done")
)
(-->
  id         "3"
  op         "describe"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.385751932"
)
(<--
  id         "3"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.392483759"
  aux        (dict ...)
  ops        (dict ...)
  status     ("done")
  versions   (dict ...)
)
(-->
  id                                 "4"
  op                                 "eval"
  session                            "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp                         "2023-05-05 20:47:09.412232201"
  code                               "(when-let [requires (resolve 'clojure.main/repl-requires)]
 ..."
  column                             1
  file                               "*cider-repl Temp/cider-test:localhost:40759(clj)*"
  inhibit-cider-middleware           "true"
  line                               43
  nrepl.middleware.print/buffer-size 4096
  nrepl.middleware.print/options     (dict ...)
  nrepl.middleware.print/print       "cider.nrepl.pprint/pprint"
  nrepl.middleware.print/quota       1048576
  nrepl.middleware.print/stream?     "1"
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.541059422"
  value      "nil"
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.583398517"
  ns         "user"
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.583575830"
  status     ("done")
)
(-->
  id         "5"
  op         "out-subscribe"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:09.583997783"
)
(-->
  id                                 "6"
  op                                 "init-debugger"
  session                            "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp                         "2023-05-05 20:47:09.584353759"
  nrepl.middleware.print/buffer-size 4096
  nrepl.middleware.print/options     (dict ...)
  nrepl.middleware.print/print       "cider.nrepl.pprint/pprint"
  nrepl.middleware.print/quota       1048576
  nrepl.middleware.print/stream?     "1"
)
(-->
  id         "7"
  op         "eval"
  session    "44d025b7-1a3f-44ab-8624-8b233436d455"
  time-stamp "2023-05-05 20:47:09.584721929"
  code       "cljs.core/demunge"
)
(<--
  id            "5"
  session       "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp    "2023-05-05 20:47:09.683080941"
  out-subscribe "24fb3ff6-b603-402e-909f-713faa1812d9"
  status        ("done")
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.475855447"
  err        "ERROR:ERROR:  Unhandled REPL handler exception processing me..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.476322236"
  err        "1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.mi..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.479189883"
  err        "Syntax error macroexpanding at (cider/nrepl/inlined/deps/orc..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.480715059"
  err        "pplyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.482009299"
  err        "voke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invok..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.483352785"
  err        "183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at ..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.484394492"
  err        ".invokeStatic(core.clj:6038)
	at clojure.core$require.doInvo..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.485377751"
  err        "933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clo..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.486471057"
  err        "mpiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT...."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.487456777"
  err        "re.core$require.doInvoke(core.clj:6038)
	at clojure.lang.Res..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.488380500"
  err        "l.middleware$wrap_conj_descriptor$fn__962.invoke(middleware...."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.489721141"
  err        "
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWo..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.490658950"
  err        ".inlined.deps.orchard.v0v11v0.orchard.java.parser$eval6303.i..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.491297897"
  err        "ore.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.cl..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.491998695"
  err        "jure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.j..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.492531697"
  err        "1v0.orchard.info$eval6160$loading__6789__auto____6161.invoke..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.493017148"
  err        "voke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.j..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.535539362"
  err        "sourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:4..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.535822448"
  err        "er.nrepl.middleware.debug$eval3961$loading__6789__auto____39..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.535971203"
  err        "estFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.536110257"
  err        "at cider.nrepl$wrap_debug$fn__2388.invoke(nrepl.clj:163)
	at..."
)
(<--
  id         "4"
  session    "24fb3ff6-b603-402e-909f-713faa1812d9"
  time-stamp "2023-05-05 20:47:11.536247721"
  err        "r.clj:141)
	at nrepl.server$handle_STAR_.invokeStatic(server..."
)
```

**Comment by khinsen** [comment]
Thanks a lot @vemv, that fixes the failure! I made a PR (#3340) to add "full JDK" to the prerequisites listed in the documentation. It's not obvious why CIDER needs a full JDK, nor does the error message point to this as the cause, so it's better to be explicit about this.
