### ISSUE TITLE
cider-connect prompts for "Lisp Expression"

### ISSUE THREAD

**Issue by terjesb** [clojure-emacs/cider#615]
Have been running on master for quite some time without issues, updating frequently. Which is great. Today, after M-x cider-connect and entering host and port, I see:

```
Error: (wrong-type-argument stringp nil)
```

and then after a couple of seconds:

```
Lisp Expression:
```

CIDER 0.7.0snapshot (package: 20140610.608)
GNU Emacs 24.3.91.1 (x86_64-apple-darwin)
Tried both 24.3 and 24.4 pretest

Both with and without cider-nrepl 0.7.0-SNAPSHOT on the server-side.
Both from a scratch buffer and a clojure-mode buffer.
Using company-mode.

If you need more context, please let me know how to provide it.

**Comment by NightMachinary** [comment]
I get this when I type outside parentheses and company-mode is active:
![image](https://user-images.githubusercontent.com/36224762/136033891-4f3edde2-128b-49cc-a4fc-2b9bd073bf41.png)

Any ideas?

**Comment by vemv** [comment]
Personally I see this very occasionally. I'd say it's related to whether a connection was successfully/properly established but don't quote me on that.

* Does this always happen? Is it reproducible? (that is, in your environment)
* Is any error logged to `*cider-error*` or a similar buffer?

**Comment by NightMachinary** [comment]
> Personally I see this very occasionally. I'd say it's related to whether a connection was successfully/properly established but don't quote me on that.
> 
> * Does this always happen? Is it reproducible? (that is, in your environment)
> * Is any error logged to `*cider-error*` or a similar buffer?

It's 100% reproducible, fortunately or unfortunately. My CIDER buffers are also very slow. Profiling it, `eldoc-cider` is taking up a lot of CPU. Disabling company-mode does solve the 'lisp expression:` issue, but not the general hanginess.

There is no `*cider-error*`, but the REPL is like this:
```
DEPRECATED: Libs must be qualified, change compliment => compliment/compliment 
DEPRECATED: Libs must be qualified, change nrepl => nrepl/nrepl 
nREPL server started on port 53562 on host localhost - nrepl://localhost:53562
;; Connected to nREPL server - nrepl://localhost:53562
;; CIDER 1.1.0snapshot, nREPL 0.8.2
;; Clojure 1.10.3, Java 1.8.0_152-release
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {com.cemerick/pomegranate {:mvn/version "0.4.0"} org.tcrawley/dynapath {:mvn/version "0.2.5"} nrepl/nrepl {:mvn/version "0.8.3"} me.raynes/fs {:mvn/version "1.4.6"} compliment {:mvn/version "0.3.11"} nrepl {:mvn/version "0.8.2"} refactor-nrepl/refactor-nrepl {:mvn/version "2.5.1"} cider/cider-nrepl {:mvn/version "0.25.9"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I am using Doom's CIDER config, along with Lispyville.

**Comment by NightMachinary** [comment]
I disabled Lispyville, and tried again, and now I see:
```
nREPL server started on port 56380 on host localhost - nrepl://localhost:56380
;; Connected to nREPL server - nrepl://localhost:56380
;; CIDER 1.1.0snapshot, nREPL 0.8.3
;; Clojure 1.10.3, Java 1.8.0_152-release
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.3"} refactor-nrepl/refactor-nrepl {:mvn/version "2.5.1"} cider/cider-nrepl {:mvn/version "0.25.9"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl
ERROR: Unhandled REPL handler exception processing message {:op eldoc, :ns user, :sym nREPL, :session 3c7253ca-6ce5-4b73-b64d-f20f78c4c6e3, :id 11}
java.lang.ClassNotFoundException: com.sun.tools.javac.util.List
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java.legacy_parser$parse_java.invokeStatic(legacy_parser.clj:88)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java.legacy_parser$parse_java.invoke(legacy_parser.clj:66)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java.legacy_parser$source_info.invokeStatic(legacy_parser.clj:274)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java.legacy_parser$source_info.invoke(legacy_parser.clj:265)
	at clojure.lang.Var.invoke(Var.java:384)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$source_info.invokeStatic(java.clj:144)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$source_info.invoke(java.clj:139)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$class_info_STAR_.invokeStatic(java.clj:223)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$class_info_STAR_.invoke(java.clj:214)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$class_info.invokeStatic(java.clj:261)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$class_info.invoke(java.clj:253)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$resolve_class.invokeStatic(java.clj:340)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$resolve_class.invoke(java.clj:331)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$resolve_symbol.invokeStatic(java.clj:371)
	at cider.nrepl.inlined_deps.orchard.v0v6v5.orchard.java$resolve_symbol.invoke(java.clj:357)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invokeStatic(stacktrace.clj:84)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invoke(stacktrace.clj:63)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at cider.nrepl.middleware.stacktrace$analyze_frame.invokeStatic(stacktrace.clj:180)
	at cider.nrepl.middleware.stacktrace$analyze_frame.invoke(stacktrace.clj:177)
	at clojure.core$map$fn__5884.invoke(core.clj:2759)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5401.invokeStatic(core.clj:55)
	at clojure.core$first__5401.invoke(core.clj:55)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invokeStatic(stacktrace.clj:168)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invoke(stacktrace.clj:164)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invokeStatic(stacktrace.clj:186)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invoke(stacktrace.clj:182)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invokeStatic(stacktrace.clj:290)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invoke(stacktrace.clj:281)
	at cider.nrepl.middleware.stacktrace$analyze_causes$fn__6579.invoke(stacktrace.clj:315)
	at clojure.core$map$fn__5880$fn__5881.invoke(core.clj:2746)
	at clojure.core$take_while$fn__5931$fn__5932.invoke(core.clj:2905)
	at clojure.lang.Iterate.reduce(Iterate.java:81)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6901)
	at clojure.core$into.invoke(core.clj:6889)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invokeStatic(stacktrace.clj:314)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invoke(stacktrace.clj:306)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl.middleware.util.error_handling$pp_stacktrace.invokeStatic(error_handling.clj:44)
	at cider.nrepl.middleware.util.error_handling$pp_stacktrace.invoke(error_handling.clj:39)
	at cider.nrepl.middleware.util.error_handling$base_error_response.invokeStatic(error_handling.clj:54)
	at cider.nrepl.middleware.util.error_handling$base_error_response.doInvoke(error_handling.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at cider.nrepl.middleware.util.error_handling$eval3120$fn__3121.invoke(error_handling.clj:129)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at cider.nrepl.middleware.util.error_handling$eval3132$fn__3133.invoke(error_handling.clj:140)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at cider.nrepl.middleware.util.error_handling$eval3136$fn__3137.invoke(error_handling.clj:143)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at cider.nrepl.middleware.info$handle_info.invokeStatic(info.clj:96)
	at cider.nrepl.middleware.info$handle_info.invoke(info.clj:95)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_info$fn__2903.invoke(nrepl.clj:203)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_complete$fn__2869.invoke(nrepl.clj:139)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_spec$fn__2969.invoke(nrepl.clj:401)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__994.invoke(interruptible_eval.clj:154)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_out$fn__2937.invoke(nrepl.clj:319)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_inspect$fn__2913.invoke(nrepl.clj:222)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_debug$fn__2879.invoke(nrepl.clj:159)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.load_file$wrap_load_file$fn__1460.invoke(load_file.clj:81)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_enlighten$fn__2887.invoke(nrepl.clj:185)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.session$add_stdin$fn__1110.invoke(session.clj:363)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__929.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_undef$fn__3009.invoke(nrepl.clj:478)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_tracker$fn__3001.invoke(nrepl.clj:467)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_resource$fn__2961.invoke(nrepl.clj:391)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_content_type$fn__2837.invoke(nrepl.clj:105)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_test$fn__2985.invoke(nrepl.clj:427)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__896.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.sideloader$wrap_sideloader$fn__1547.invoke(sideloader.clj:104)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.middleware.session$session$fn__1095.invoke(session.clj:309)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at cider.nrepl$wrap_version$fn__3019.invoke(nrepl.clj:486)
	at nrepl.middleware$wrap_conj_descriptor$fn__660.invoke(middleware.clj:16)
	at nrepl.server$default_handler$fn__1591.invoke(server.clj:130)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
	at nrepl.server$handle_STAR_.invoke(server.clj:19)
	at nrepl.server$handle$fn__1562.invoke(server.clj:39)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

user> 
```

The error seems related to eldoc being slow as hell.

**Comment by vemv** [comment]
> Startup: /usr/local/bin/clojure -Sdeps '{:deps {com.cemerick/pomegranate {:mvn/version "0.4.0"} org.tcrawley/dynapath {:mvn/version "0.2.5"} nrepl/nrepl {:mvn/version "0.8.3"} me.raynes/fs {:mvn/version "1.4.6"} compliment {:mvn/version "0.3.11"} nrepl {:mvn/version "0.8.2"} refactor-nrepl/refactor-nrepl {:mvn/version "2.5.1"} cider/cider-nrepl {:mvn/version "0.25.9"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl

cider-nrepl latest is 0.27.2. Also quite importantly, refactor-nrepl latest is 3.0.0-alpha12.

If you force cider.el and clj-refactor.el to be at their latest snapshot versions, the related JVM middleware will also get updated.

> java.lang.ClassNotFoundException: com.sun.tools.javac.util.List

That is certainly fixable by setting the first JVM option described here https://github.com/clojure-emacs/orchard/tree/fa5bbb670bd502e59dfa61cfa8e65def38897239#configuration-options at startup time, for the `/usr/local/bin/clojure` command. Not super sure of how that is accomplished for deps.edn, but should be doable.

The issue is tracked at https://github.com/clojure-emacs/orchard/issues/105. (We plan fixing it soon but we were hesitant about pulling the plug on a feature altogether)

Note that said JVM option requires a recent-enough jvm middleware; the option wasn't available 27.0.

Don't hesitate to report back - these help us a lot!

**Comment by NightMachinary** [comment]
@vemv I changed my PATH so that now I use Java 15 instead of 8. Things improved a lot, and CIDER now seems usable. I still get this error when I activate lispy:
```
Error (nrepl-connected-hook): Error running hook "lispy--clojure-eval-hook-lambda" because: (eval-error . Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:435).
```

But I guess it's a lispy issue? Things also still work despite the error. I will check out the issue you linked, perhaps it will solve this error.

> If you force cider.el and clj-refactor.el to be at their latest snapshot versions, the related JVM middleware will also get updated.

Is there a particular reason I should upgrade to the bleeding edge? Package pinning in Doom is done to provide some stability.

**Comment by vemv** [comment]
Both series of JDKs (8 and 9+) have their own flaws unfortunately 😞 both are fixed by setting the mentioned JVM option. It's a pretty unfortunate situation - we've kept an eye on properly fixing this for everyone for all of 2021.

A major CIDER release is coming in ~3 weeks or so, we hope it will be a really nice and clean one with both stability and new features especially for Java IDE-like features.

> Is there a particular reason I should upgrade to the bleeding edge? Package pinning in Doom is done to provide some stability.

I understand the sentiment. The bleeding edge is currently simply 'latest bugfixes' so we don't foresee a risk. We really try not to inflict breaking changes. Maybe you can bump to $current and stay there for a while - no need to _constantly_ update :)

As mentioned, at least ensure cider-nrepl is >= 0.27.0.

Cheers - V
